local h = require("tests.helper")
local R = h.loadLib()
local Accordion, Create = R.Accordion, R.Create

local function parentWithLayout()
  local p = Create("Frame", {})
  Create("UIListLayout", { Parent = p })
  return p
end

h.describe("accordion", function()
  h.it("container clips and is auto-size None (tween-controlled)", function()
    local p = parentWithLayout()
    local acc = Accordion.new({ Parent = p, Title = "Advanced", Icon = "settings-2" })
    h.expect(acc.Container.ClipsDescendants).toBe(true)
    h.expect(acc.Container.AutomaticSize.Name).toBe("None")
    h.expect(acc.Container.Parent).toBe(p)
  end)
  h.it("content uses UIListLayout + AutomaticSize.Y", function()
    local p = parentWithLayout()
    local acc = Accordion.new({ Parent = p, Title = "X" })
    h.expect(acc.Content.AutomaticSize.Name).toBe("Y")
    h.expect(acc.Content:FindFirstChildOfClass("UIListLayout") ~= nil).toBeTruthy()
  end)
  h.it("Toggle flips state and fires exactly one container size tween", function()
    local p = parentWithLayout()
    local acc = Accordion.new({ Parent = p, Title = "X", Expanded = false })
    h.expect(acc:IsExpanded()).toBe(false)
    h.mock.lastTween = nil
    acc:Toggle()
    h.expect(acc:IsExpanded()).toBe(true)
    h.expect(h.mock.lastTween ~= nil).toBeTruthy()
    h.expect(h.mock.lastTween.Instance).toBe(acc.Container)  -- the ONE tween targets the container
  end)
  h.it("MountRow assigns incrementing LayoutOrder under Content", function()
    local p = parentWithLayout()
    local acc = Accordion.new({ Parent = p, Title = "X" })
    local a = Create("Frame", {}); local b = Create("Frame", {})
    local o1 = acc.MountRow(a); local o2 = acc.MountRow(b)
    h.expect(a.Parent).toBe(acc.Content)
    h.expect(o2 > o1).toBeTruthy()
  end)
end)

h.run()
