local h = require("tests.helper")
local R = h.loadLib()
local Accordion, Create = R.Accordion, R.Create

local function parentWithLayout()
  local p = Create("Frame", {})
  Create("UIListLayout", { Parent = p })
  return p
end

h.describe("accordion", function()
  h.it("container clips and is auto-size None (tween-controlled)", function()
    local p = parentWithLayout()
    local acc = Accordion.new({ Parent = p, Title = "Advanced", Icon = "settings-2" })
    h.expect(acc.Container.ClipsDescendants).toBe(true)
    h.expect(acc.Container.AutomaticSize.Name).toBe("None")
    h.expect(acc.Container.Parent).toBe(p)
  end)
  h.it("content uses UIListLayout + AutomaticSize.Y", function()
    local p = parentWithLayout()
    local acc = Accordion.new({ Parent = p, Title = "X" })
    h.expect(acc.Content.AutomaticSize.Name).toBe("Y")
    h.expect(acc.Content:FindFirstChildOfClass("UIListLayout") ~= nil).toBeTruthy()
  end)
  h.it("renders as a bordered card with a divider that shows only when expanded", function()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "Adv", Expanded = false })
    h.expect(acc.Container:FindFirstChildOfClass("UIStroke") ~= nil).toBeTruthy()
    local divider = acc.Container:FindFirstChild("Divider")
    h.expect(divider ~= nil).toBeTruthy()
    h.expect(divider.Visible).toBe(false)
    acc:Expand()
    h.expect(divider.Visible).toBe(true)
  end)
  h.it("does not recolor the container on header hover", function()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "X" })
    local base = acc.Container.BackgroundColor3
    acc.Header.MouseEnter:Fire()
    h.expect(acc.Container.BackgroundColor3).toBe(base)
  end)
  h.it("MountRow assigns incrementing LayoutOrder under Content", function()
    local p = parentWithLayout()
    local acc = Accordion.new({ Parent = p, Title = "X" })
    local a = Create("Frame", {}); local b = Create("Frame", {})
    local o1 = acc.MountRow(a); local o2 = acc.MountRow(b)
    h.expect(a.Parent).toBe(acc.Content)
    h.expect(o2 > o1).toBeTruthy()
  end)
  -- Motion (Task 2): caret rotation + spring height + slide reveal
  h.it("collapsed by default: header height, caret unrotated, content hidden", function()
    local a = Accordion.new({ Parent = Create("Frame", {}), Title = "Sec" })
    h.expect(a.Container.Size.Y.Offset).toBe(34)
    h.expect(a.Header:FindFirstChild("Caret").Rotation).toBe(0)
    h.expect(a.Content.Visible).toBe(false)
  end)
  h.it("Expand rotates caret to 90, shows content, grows the container", function()
    local a = Accordion.new({ Parent = Create("Frame", {}), Title = "Sec" })
    a:Expand()
    h.expect(a:IsExpanded()).toBe(true)
    h.expect(a.Content.Visible).toBe(true)
    h.expect(a.Header:FindFirstChild("Caret").Rotation).toBe(90)
    h.expect(a.Container.Size.Y.Offset > 34).toBeTruthy()
  end)
  h.it("Collapse rotates caret back to 0, hides content, returns to header height", function()
    local a = Accordion.new({ Parent = Create("Frame", {}), Title = "Sec", Expanded = true })
    a:Collapse()
    h.expect(a:IsExpanded()).toBe(false)
    h.expect(a.Content.Visible).toBe(false)
    h.expect(a.Header:FindFirstChild("Caret").Rotation).toBe(0)
    h.expect(a.Container.Size.Y.Offset).toBe(34)
  end)
  h.it("Toggle flips expansion and returns the new state", function()
    local a = Accordion.new({ Parent = Create("Frame", {}), Title = "Sec" })
    h.expect(a:Toggle()).toBe(true)
    h.expect(a:Toggle()).toBe(false)
  end)
  -- Regression: a child's height settles a render step AFTER it is added (TextLabel AutomaticSize,
  -- wrapped/reactive paragraphs). The container (AutomaticSize=None, ClipsDescendants) must re-derive
  -- its height on the next Heartbeat or it stays sized for the un-settled child and clips the rest.
  local gap = R.Theme.Spacing.gap
  local inputY = R.Theme.Spacing.inputY
  h.it("AddParagraph/AddButton schedule a deferred re-measure so tall content is not clipped", function()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "X", Expanded = true })
    local layout = acc.Content:FindFirstChildOfClass("UIListLayout")
    acc:AddParagraph("a\nb\nc\nd\ne\nf")   -- tall content; its AutomaticSize lands next frame
    acc:AddButton({ Text = "Go" })
    layout.AbsoluteContentSize = h.roblox.Vector2.new(0, 120) -- engine settles the content height
    h.mock.stepHeartbeat(0)                                   -- Heartbeat:Once -> deferred reflow runs
    h.expect(acc.Container.Size.Y.Offset).toBe(34 + gap + 120 + inputY)
  end)
  h.it("MountRow schedules a deferred re-measure", function()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "X", Expanded = true })
    local layout = acc.Content:FindFirstChildOfClass("UIListLayout")
    acc.MountRow(Create("Frame", {}))
    layout.AbsoluteContentSize = h.roblox.Vector2.new(0, 90)
    h.mock.stepHeartbeat(0)
    h.expect(acc.Container.Size.Y.Offset).toBe(34 + gap + 90 + inputY)
  end)
  h.it("a collapsed accordion does not grow on a deferred re-measure", function()
    local acc = Accordion.new({ Parent = parentWithLayout(), Title = "X", Expanded = false })
    local layout = acc.Content:FindFirstChildOfClass("UIListLayout")
    acc.MountRow(Create("Frame", {}))
    layout.AbsoluteContentSize = h.roblox.Vector2.new(0, 200)
    h.mock.stepHeartbeat(0)
    h.expect(acc.Container.Size.Y.Offset).toBe(34)            -- stays header-height while collapsed
  end)
end)

h.run()
