local h = require("tests.helper")
local R = h.loadLib()
local Accordion, Create = R.Accordion, R.Create

h.describe("accordion", function()
  h.it("collapsed by default: header height, caret unrotated, content hidden", function()
    local a = Accordion.new({ Parent = Create("Frame", {}), Title = "Sec" })
    h.expect(a.Container.Size.Y.Offset).toBe(34)
    h.expect(a.Header:FindFirstChild("Caret").Rotation).toBe(0)
    h.expect(a.Content.Visible).toBe(false)
  end)
  h.it("Expand rotates caret to 90, shows content, grows the container", function()
    local a = Accordion.new({ Parent = Create("Frame", {}), Title = "Sec" })
    a:Expand()
    h.expect(a:IsExpanded()).toBe(true)
    h.expect(a.Content.Visible).toBe(true)
    h.expect(a.Header:FindFirstChild("Caret").Rotation).toBe(90)
    h.expect(a.Container.Size.Y.Offset > 34).toBeTruthy()
  end)
  h.it("Collapse rotates caret back to 0, hides content, returns to header height", function()
    local a = Accordion.new({ Parent = Create("Frame", {}), Title = "Sec", Expanded = true })
    a:Collapse()
    h.expect(a:IsExpanded()).toBe(false)
    h.expect(a.Content.Visible).toBe(false)
    h.expect(a.Header:FindFirstChild("Caret").Rotation).toBe(0)
    h.expect(a.Container.Size.Y.Offset).toBe(34)
  end)
  h.it("Toggle flips expansion and returns the new state", function()
    local a = Accordion.new({ Parent = Create("Frame", {}), Title = "Sec" })
    h.expect(a:Toggle()).toBe(true)
    h.expect(a:Toggle()).toBe(false)
  end)
end)

h.run()
