local h = require("tests.helper")
local R = h.loadLib()
local Acrylic, Theme, Create = R.Acrylic, R.Theme, R.Create

h.describe("acrylic", function()
  h.it("decorate adds translucent fill + sheen + stroke + noise layer", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme)
    h.expect(f.BackgroundColor3.R8).toBe(24)          -- card
    h.expect(f.BackgroundTransparency).toBe(0.12)     -- frosted (translucent but readable)
    h.expect(f:FindFirstChildOfClass("UIGradient") ~= nil).toBeTruthy()
    h.expect(f:FindFirstChildOfClass("UIStroke") ~= nil).toBeTruthy()
    h.expect(f:FindFirstChild("AcrylicNoise") ~= nil).toBeTruthy()
  end)
  h.it("transparency option overrides the default frost", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { transparency = 0.25 })
    h.expect(f.BackgroundTransparency).toBe(0.25)
  end)
  h.it("solid has no gradient/noise and is opaque", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { solid = true })
    h.expect(f.BackgroundTransparency).toBe(0)
    h.expect(f:FindFirstChildOfClass("UIGradient")).toBeNil()
    h.expect(f:FindFirstChild("AcrylicNoise")).toBeNil()
  end)
  h.it("decorate twice does not duplicate stroke", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme); Acrylic.decorate(f, Theme)
    local strokes = 0
    for _, c in ipairs(f:GetChildren()) do if c.ClassName == "UIStroke" then strokes = strokes + 1 end end
    h.expect(strokes).toBe(1)
  end)
  h.it("base option overrides the fill colour", function()
    local f = Create("Frame", {})
    Acrylic.decorate(f, Theme, { base = Theme.Colors.background })
    h.expect(f.BackgroundColor3.R8).toBe(Theme.Colors.background.R8)
  end)
  h.it("blur handle toggles Enabled and Size", function()
    local b = Acrylic.blur({ size = 20 })
    h.expect(b.Instance.ClassName).toBe("BlurEffect")
    h.expect(b.Instance.Size).toBe(20)
    b.SetEnabled(false)
    h.expect(b.Instance.Enabled).toBe(false)
    h.expect(b.Instance.Size).toBe(0)
    b.SetEnabled(true)
    h.expect(b.Instance.Size).toBe(20)
  end)
end)

h.run()
