local h = require("tests.helper")
local Animate = h.loadLib().Animate

h.describe("animate", function()
  h.it("info builds TweenInfo with Quart/Out defaults", function()
    local i = Animate.info(0.18)
    h.expect(i.Time).toBe(0.18)
    h.expect(i.EasingStyle.Name).toBe("Quart")
    h.expect(i.EasingDirection.Name).toBe("Out")
  end)
  h.it("to() plays a tween and applies goal", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.to(f, "fast", { BackgroundTransparency = 0.15 })
    h.expect(h.mock.lastTween.played).toBeTruthy()
    h.expect(f.BackgroundTransparency).toBe(0.15)
  end)
  h.it("resolves motion-key durations", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.to(f, "slow", { X = 1 })
    h.expect(h.mock.lastTween.Info.Time).toBe(0.28)
  end)
  h.it("pop adds a UIScale and tweens it to 1 with Back/Out", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.pop(f, "base")
    local us = f:FindFirstChildOfClass("UIScale")
    h.expect(us ~= nil).toBeTruthy()
    h.expect(h.mock.lastTween.Instance).toBe(us)
    h.expect(h.mock.lastTween.Goal.Scale).toBe(1)
    h.expect(h.mock.lastTween.Info.EasingStyle.Name).toBe("Back")
  end)
end)

h.run()
