local h = require("tests.helper")
local Animate = h.loadLib().Animate

h.describe("animate", function()
  h.it("info builds TweenInfo with Quart/Out defaults", function()
    local i = Animate.info(0.18)
    h.expect(i.Time).toBe(0.18)
    h.expect(i.EasingStyle.Name).toBe("Quart")
    h.expect(i.EasingDirection.Name).toBe("Out")
  end)
  h.it("to() plays a tween and applies goal", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.to(f, "fast", { BackgroundTransparency = 0.15 })
    h.expect(h.mock.lastTween.played).toBeTruthy()
    h.expect(f.BackgroundTransparency).toBe(0.15)
  end)
  h.it("resolves motion-key durations", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.to(f, "slow", { X = 1 })
    h.expect(h.mock.lastTween.Info.Time).toBe(0.28)
  end)
  h.it("pop adds a UIScale and tweens it to 1 with Back/Out", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.pop(f, "base")
    local us = f:FindFirstChildOfClass("UIScale")
    h.expect(us ~= nil).toBeTruthy()
    h.expect(h.mock.lastTween.Instance).toBe(us)
    h.expect(h.mock.lastTween.Goal.Scale).toBe(1)
    h.expect(h.mock.lastTween.Info.EasingStyle.Name).toBe("Back")
  end)
  h.it("setEnabled(false) applies goal instantly and returns an immediate-complete stub", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.setEnabled(false)
    local fired = false
    local tw = Animate.to(f, "fast", { BackgroundTransparency = 0.4 })
    tw.Completed:Connect(function() fired = true end)
    h.expect(f.BackgroundTransparency).toBe(0.4)
    h.expect(fired).toBe(true)
    Animate.setEnabled(true)
  end)
  h.it("toThen runs onComplete once and applies goal (enabled)", function()
    local f = h.roblox.Instance.new("Frame")
    local n = 0
    Animate.toThen(f, "fast", { X = 2 }, function() n = n + 1 end)
    h.expect(f.X).toBe(2)
    h.expect(n).toBe(1)
  end)
  h.it("toThen runs onComplete once and applies goal (disabled)", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.setEnabled(false)
    local n = 0
    Animate.toThen(f, "fast", { X = 5 }, function() n = n + 1 end)
    h.expect(f.X).toBe(5)
    h.expect(n).toBe(1)
    Animate.setEnabled(true)
  end)
  h.it("springTo tweens with Back/Out and applies goal", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.springTo(f, "base", { Scale = 1 })
    h.expect(h.mock.lastTween.Info.EasingStyle.Name).toBe("Back")
    h.expect(h.mock.lastTween.Info.EasingDirection.Name).toBe("Out")
    h.expect(f.Scale).toBe(1)
  end)
  h.it("rotateTo sets a Rotation goal with a Back default", function()
    local f = h.roblox.Instance.new("Frame")
    Animate.rotateTo(f, "base", 90)
    h.expect(f.Rotation).toBe(90)
    h.expect(h.mock.lastTween.Info.EasingStyle.Name).toBe("Back")
  end)
end)

h.run()
