local h = require("tests.helper")
local Asset = h.loadLib().Asset
h.describe("asset", function()
  h.it("passes through rbxasset content ids", function()
    h.expect(Asset.image("rbxassetid://42")).toBe("rbxassetid://42")
    h.expect(Asset.image("rbxthumb://type=Asset&id=1&w=150&h=150")).toBe("rbxthumb://type=Asset&id=1&w=150&h=150")
  end)
  h.it("coerces a bare numeric id", function()
    h.expect(Asset.image("99")).toBe("rbxassetid://99")
  end)
  h.it("returns nil for a URL when no executor globals exist, without erroring", function()
    h.expect(Asset.image("https://example.com/x.png")).toBe(nil)
  end)
  h.it("returns nil for nil / non-string", function()
    h.expect(Asset.image(nil)).toBe(nil)
    h.expect(Asset.image(123)).toBe(nil)
  end)
end)
h.run()
