local h = require("tests.helper")
local Config = h.requireModule("core.config")

h.describe("config", function()
  h.it("register + get returns default", function()
    local c = Config.new({ FileName = "T" })
    c:Register("autofarm", false, function() end)
    h.expect(c:Get("autofarm")).toBe(false)
  end)
  h.it("set then save then load round-trips", function()
    local c = Config.new({ FileName = "T", AutoSave = false })
    c:Register("speed", 50, function() end)
    c:Set("speed", 80)
    c:Save()
    local c2 = Config.new({ FileName = "T" })
    local applied
    c2:Register("speed", 50, function(v) applied = v end)
    c2:Load()
    h.expect(c2:Get("speed")).toBe(80)
    h.expect(applied).toBe(80)
  end)
  h.it("reset restores defaults and calls setValue", function()
    local c = Config.new({ FileName = "T2", AutoSave = false })
    local current
    c:Register("toggle", false, function(v) current = v end)
    c:Set("toggle", true)
    c:Reset()
    h.expect(c:Get("toggle")).toBe(false)
    h.expect(current).toBe(false)
  end)
  h.it("reset ClearFile deletes the file", function()
    local c = Config.new({ FileName = "T3", AutoSave = false })
    c:Register("a", 1, function() end)
    c:Save()
    h.expect(h.roblox.isfile("EzUI/T3.json")).toBeTruthy()
    c:Reset({ ClearFile = true })
    h.expect(h.roblox.isfile("EzUI/T3.json")).toBe(false)
  end)
  h.it("FileName is the saved file, not a folder (Default profile)", function()
    local c = Config.new({ FolderName = "Hub", FileName = "settings", AutoSave = false })
    c:Register("a", 1, function() end)
    c:Save()
    -- documented: <FolderName>/<FileName>.json, NOT <FolderName>/<FileName>/Default.json
    h.expect(h.roblox.isfile("Hub/settings.json")).toBeTruthy()
    h.expect(h.roblox.isfile("Hub/settings/Default.json")).toBe(false)
  end)
  h.it("AutoLoad restores values on construction without an explicit Load", function()
    local a = Config.new({ FileName = "Auto", AutoSave = false })
    a:Register("speed", 50, function() end)
    a:Set("speed", 77)
    a:Save()
    -- AutoLoad defaults to true: a fresh config reads from disk on startup
    local b = Config.new({ FileName = "Auto" })
    h.expect(b:Get("speed")).toBe(77)
  end)
  h.it("AutoLoad = false does not read from disk on construction", function()
    local a = Config.new({ FileName = "NoAuto", AutoSave = false })
    a:Register("speed", 50, function() end)
    a:Set("speed", 77)
    a:Save()
    local b = Config.new({ FileName = "NoAuto", AutoLoad = false })
    h.expect(b:Get("speed")).toBe(nil)
  end)
  h.it("supports named profiles with a Default and list/switch/delete", function()
    local cfg = Config.new({ FileName = "Prof", AutoSave = false })
    cfg:Register("a", 1)
    h.expect(cfg:ActiveProfile()).toBe("Default")
    cfg:Set("a", 1); cfg:Save()
    cfg:SwitchProfile("PvP"); cfg:Set("a", 9); cfg:Save()
    h.expect(cfg:ActiveProfile()).toBe("PvP")
    -- Default lives at <folder>/<file>.json; named profiles live in the <folder>/<file>/ subfolder
    h.expect(h.roblox.isfile("Prof.json")).toBe(false)
    h.expect(h.roblox.isfile("EzUI/Prof.json")).toBeTruthy()
    h.expect(h.roblox.isfile("EzUI/Prof/PvP.json")).toBeTruthy()
    local has = {}; for _, n in ipairs(cfg:ListProfiles()) do has[n] = true end
    h.expect(has.Default).toBe(true); h.expect(has.PvP).toBe(true)
    cfg:DeleteProfile("PvP")
    local has2 = {}; for _, n in ipairs(cfg:ListProfiles()) do has2[n] = true end
    h.expect(has2.PvP).toBe(nil)
  end)
end)

h.run()
