local h = require("tests.helper")
local Config = h.requireModule("core.config")

h.describe("config", function()
  h.it("register + get returns default", function()
    local c = Config.new({ FileName = "T" })
    c:Register("autofarm", false, function() end)
    h.expect(c:Get("autofarm")).toBe(false)
  end)
  h.it("set then save then load round-trips", function()
    local c = Config.new({ FileName = "T", AutoSave = false })
    c:Register("speed", 50, function() end)
    c:Set("speed", 80)
    c:Save()
    local c2 = Config.new({ FileName = "T" })
    local applied
    c2:Register("speed", 50, function(v) applied = v end)
    c2:Load()
    h.expect(c2:Get("speed")).toBe(80)
    h.expect(applied).toBe(80)
  end)
  h.it("reset restores defaults and calls setValue", function()
    local c = Config.new({ FileName = "T2", AutoSave = false })
    local current
    c:Register("toggle", false, function(v) current = v end)
    c:Set("toggle", true)
    c:Reset()
    h.expect(c:Get("toggle")).toBe(false)
    h.expect(current).toBe(false)
  end)
  h.it("reset ClearFile deletes the file", function()
    local c = Config.new({ FileName = "T3", AutoSave = false })
    c:Register("a", 1, function() end)
    c:Save()
    h.expect(h.roblox.isfile("EzUI/T3.json")).toBeTruthy()
    c:Reset({ ClearFile = true })
    h.expect(h.roblox.isfile("EzUI/T3.json")).toBe(false)
  end)
end)

h.run()
