local h = require("tests.helper")
local Config = h.requireModule("core.config")

h.describe("config", function()
  h.it("register + get returns default", function()
    local c = Config.new({ FileName = "T" })
    c:Register("autofarm", false, function() end)
    h.expect(c:Get("autofarm")).toBe(false)
  end)
  h.it("set then save then load round-trips", function()
    local c = Config.new({ FileName = "T", AutoSave = false })
    c:Register("speed", 50, function() end)
    c:Set("speed", 80)
    c:Save()
    local c2 = Config.new({ FileName = "T" })
    local applied
    c2:Register("speed", 50, function(v) applied = v end)
    c2:Load()
    h.expect(c2:Get("speed")).toBe(80)
    h.expect(applied).toBe(80)
  end)
  h.it("reset restores defaults and calls setValue", function()
    local c = Config.new({ FileName = "T2", AutoSave = false })
    local current
    c:Register("toggle", false, function(v) current = v end)
    c:Set("toggle", true)
    c:Reset()
    h.expect(c:Get("toggle")).toBe(false)
    h.expect(current).toBe(false)
  end)
  h.it("reset ClearFile deletes the file", function()
    local c = Config.new({ FileName = "T3", AutoSave = false })
    c:Register("a", 1, function() end)
    c:Save()
    h.expect(h.roblox.isfile("EzUI/T3/Default.json")).toBeTruthy()
    c:Reset({ ClearFile = true })
    h.expect(h.roblox.isfile("EzUI/T3/Default.json")).toBe(false)
  end)
  h.it("supports named profiles with a Default and list/switch/delete", function()
    local cfg = Config.new({ FileName = "Prof", AutoSave = false })
    cfg:Register("a", 1)
    h.expect(cfg:ActiveProfile()).toBe("Default")
    cfg:Set("a", 1); cfg:Save()
    cfg:SwitchProfile("PvP"); cfg:Set("a", 9); cfg:Save()
    h.expect(cfg:ActiveProfile()).toBe("PvP")
    local has = {}; for _, n in ipairs(cfg:ListProfiles()) do has[n] = true end
    h.expect(has.Default).toBe(true); h.expect(has.PvP).toBe(true)
    cfg:DeleteProfile("PvP")
    local has2 = {}; for _, n in ipairs(cfg:ListProfiles()) do has2[n] = true end
    h.expect(has2.PvP).toBe(nil)
  end)
end)

h.run()
