local h = require("tests.helper")
local R = h.loadLib()

h.describe("host wiring", function()
  h.it("tab AddX mounts real controls into content", function()
    local gui = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(gui)
    local w = R.Window.new({ Title = "W", Parent = gui })
    local tab = w:AddTab({ Name = "Home" })
    local tog = tab:AddToggle({ Text = "A", Default = true })
    local btn = tab:AddButton({ Text = "Go" })
    h.expect(tog.Get()).toBe(true)
    h.expect(tog.Frame.Parent).toBe(tab.Content)
    h.expect(btn.Frame.Parent).toBe(tab.Content)
  end)
  h.it("accordion AddX mounts controls into its content", function()
    local gui = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(gui)
    local w = R.Window.new({ Title = "W", Parent = gui })
    local tab = w:AddTab({ Name = "Home" })
    local acc = tab:AddAccordion({ Title = "Adv" })
    local nb = acc:AddNumberBox({ Text = "N", Default = 1 })
    h.expect(nb.Frame.Parent).toBe(acc.Content)
  end)
  h.it("flag-aware controls persist to the window config", function()
    local gui = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(gui)
    local w = R.Window.new({ Title = "W", Parent = gui, Config = { FileName = "HW", AutoSave = false } })
    local tab = w:AddTab({ Name = "Home" })
    local tog = tab:AddToggle({ Text = "Feat", Default = false, Flag = "feat" })
    tog.Set(true)
    h.expect(w.Config:Get("feat")).toBe(true)
  end)
end)

h.run()
