local h = require("tests.helper")
local R = h.loadLib()

h.describe("host wiring", function()
  h.it("SetLocked defers the scrim toggle when capability is absent", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    local lbl = tab:AddLabel("x")
    local scrim = lbl.Frame:FindFirstChild("LockScrim")
    R.Safe._setCapabilityCheck(function() return false end)
    lbl.SetLocked(true)
    h.expect(scrim.Visible).toBe(false)        -- deferred: not applied yet (fails before the wrap)
    h.mock.stepHeartbeat(0)
    h.expect(scrim.Visible).toBe(true)         -- applied in a capability context
    R.Safe._setCapabilityCheck(nil)
  end)
  h.it("tab AddX mounts real controls into content", function()
    local gui = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(gui)
    local w = R.Window.new({ Title = "W", Parent = gui })
    local tab = w:AddTab({ Name = "Home" })
    local tog = tab:AddToggle({ Text = "A", Default = true })
    local btn = tab:AddButton({ Text = "Go" })
    h.expect(tog.Get()).toBe(true)
    h.expect(tog.Frame.Parent).toBe(tab.Content)
    h.expect(btn.Frame.Parent).toBe(tab.Content)
  end)
  h.it("accordion AddX mounts controls into its content", function()
    local gui = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(gui)
    local w = R.Window.new({ Title = "W", Parent = gui })
    local tab = w:AddTab({ Name = "Home" })
    local acc = tab:AddAccordion({ Title = "Adv" })
    local nb = acc:AddNumberBox({ Text = "N", Default = 1 })
    h.expect(nb.Frame.Parent).toBe(acc.Content)
  end)
  h.it("mounts new components (slider/colorpicker) and tooltip doesn't error", function()
    local gui = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(gui)
    local w = R.Window.new({ Title = "W", Parent = gui })
    local tab = w:AddTab({ Name = "Home" })
    local sld = tab:AddSlider({ Text = "S", Min = 0, Max = 10, Default = 5 })
    local cp = tab:AddColorPicker({ Text = "C", Default = h.roblox.Color3.fromRGB(1, 2, 3) })
    local btn = tab:AddButton({ Text = "Hover", Tooltip = "hi" })
    h.expect(sld.GetValue()).toBe(5)
    h.expect(sld.Frame.Parent).toBe(tab.Content)
    h.expect(cp.Frame.Parent).toBe(tab.Content)
    h.expect(btn.Frame.Parent).toBe(tab.Content)
  end)
  h.it("flag-aware controls persist to the window config", function()
    local gui = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(gui)
    local w = R.Window.new({ Title = "W", Parent = gui, Config = { FileName = "HW", AutoSave = false } })
    local tab = w:AddTab({ Name = "Home" })
    local tog = tab:AddToggle({ Text = "Feat", Default = false, Flag = "feat" })
    tog.Set(true)
    h.expect(w.Config:Get("feat")).toBe(true)
  end)
  h.it("AddLabel(function) shorthand wires a reactive label via the host", function()
    local gui = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(gui)
    local w = R.Window.new({ Title = "W", Parent = gui })
    local tab = w:AddTab({ Name = "Home" })
    local lbl = tab:AddLabel(function() return "live" end)   -- function arg, not string/table
    h.expect(lbl.Frame.Text).toBe("live")                    -- host routed it to opts.Text; label evaluated it
    lbl.Destroy()
  end)
end)

h.run()
