local h = require("tests.helper")
local R = h.loadLib()
h.describe("locked state", function()
  h.it("Locked control shows a shield; SetLocked toggles it", function()
    local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    local b = tab:AddButton({ Text = "Go", Locked = true })
    local shield = b.Frame:FindFirstChild("LockShield")
    h.expect(shield ~= nil).toBeTruthy()
    h.expect(shield.Visible).toBe(true)
    b.SetLocked(false)
    h.expect(shield.Visible).toBe(false)
  end)
  h.it("Window:LockAll locks all registered controls", function()
    local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    local t1 = tab:AddToggle({ Text = "a" }); local t2 = tab:AddSlider({ Text = "b", Min = 0, Max = 1 })
    w:LockAll()
    h.expect(t1.Frame:FindFirstChild("LockShield").Visible).toBe(true)
    h.expect(t2.Frame:FindFirstChild("LockShield").Visible).toBe(true)
    w:UnlockAll()
    h.expect(t1.Frame:FindFirstChild("LockShield").Visible).toBe(false)
  end)
end)
h.run()
