local h = require("tests.helper")
local Icons = h.requireModule("core.icons")

h.describe("icons", function()
  h.it("curated set includes chrome icons", function()
    h.expect(Icons.data["chevron-right"] ~= nil).toBeTruthy()
    h.expect(Icons.data["home"] ~= nil).toBeTruthy()
  end)
  h.it("house alias resolves to home", function()
    h.expect(Icons.data["house"]).toBeNil()       -- not a raw data key
    h.expect(Icons.get("house") ~= nil).toBeTruthy() -- but get() aliases it
  end)
  h.it("get returns rbxassetid + both rect props", function()
    local a = Icons.get("house")
    h.expect(tostring(a.Id):sub(1, 13)).toBe("rbxassetid://")
    h.expect(a.ImageRectSize.X).toBe(48)
  end)
  h.it("apply sets image + tint, returns true", function()
    local img = h.roblox.Instance.new("ImageLabel")
    local ok = Icons.apply(img, "play", h.roblox.Color3.fromRGB(250, 250, 250))
    h.expect(ok).toBeTruthy()
    h.expect(img.ImageColor3.R8).toBe(250)
    h.expect(img.ImageRectOffset ~= nil).toBeTruthy()
  end)
  h.it("unknown icon returns nil/false", function()
    h.expect(Icons.get("definitely-not-an-icon")).toBeNil()
    local img = h.roblox.Instance.new("ImageLabel")
    h.expect(Icons.apply(img, "definitely-not-an-icon")).toBe(false)
  end)
end)

h.run()
