local h = require("tests.helper")
local R = h.loadLib(); local Image, Create = R.Image, R.Create
h.describe("image", function()
  h.it("sets rbxassetid image", function()
    local i = Image.new({ Parent = Create("Frame", {}), Image = "rbxassetid://123", LayoutOrder = 1 })
    h.expect(i.Frame.Image).toBe("rbxassetid://123")
    h.expect(i.Frame.ClassName).toBe("ImageLabel")
  end)
  h.it("Lucide name resolves via Icons", function()
    local i = Image.new({ Lucide = "home" })
    h.expect(tostring(i.Frame.Image):sub(1, 13)).toBe("rbxassetid://")
  end)
  h.it("SetImage defers the image write when capability is absent", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local im = R.Image.new({ Image = "rbxassetid://1", Parent = R.Create("Frame", {}) })
    R.Safe._setCapabilityCheck(function() return false end)
    im.SetImage("rbxassetid://2")
    h.expect(im.Frame.Image).toBe("rbxassetid://1")   -- deferred: not applied yet (fails before the wrap)
    h.mock.stepHeartbeat(0)
    h.expect(im.Frame.Image).toBe("rbxassetid://2")   -- applied in a capability context
    R.Safe._setCapabilityCheck(nil)
  end)
end)
h.run()
