local h = require("tests.helper")
local R = h.loadLib(); local Image, Create = R.Image, R.Create
h.describe("image", function()
  h.it("sets rbxassetid image", function()
    local i = Image.new({ Parent = Create("Frame", {}), Image = "rbxassetid://123", LayoutOrder = 1 })
    h.expect(i.Frame.Image).toBe("rbxassetid://123")
    h.expect(i.Frame.ClassName).toBe("ImageLabel")
  end)
  h.it("Lucide name resolves via Icons", function()
    local i = Image.new({ Lucide = "home" })
    h.expect(tostring(i.Frame.Image):sub(1, 13)).toBe("rbxassetid://")
  end)
end)
h.run()
