local h = require("tests.helper")
local R = h.loadLib(); local Keybind, Create, Config = R.Keybind, R.Create, R.Config
h.describe("keybind", function()
  h.it("default key persists by name and restores", function()
    local cfg = Config.new({ FileName = "KB", AutoSave = false })
    local k = Keybind.new({ Parent = Create("Frame", {}), Text = "Panic", Default = h.roblox.Enum.KeyCode.P, Flag = "panic", Config = cfg })
    h.expect(k.GetKey().Name).toBe("P")
    h.expect(cfg:Get("panic")).toBe("P")
  end)
  h.it("fires Callback when bound key pressed", function()
    local fired = 0
    local k = Keybind.new({ Text = "Go", Default = h.roblox.Enum.KeyCode.E, Callback = function() fired = fired + 1 end })
    local uis = h.roblox.game:GetService("UserInputService")
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.E, UserInputType = h.roblox.Enum.UserInputType.Keyboard }, false)
    h.expect(fired).toBe(1)
  end)
end)
h.run()
