local h = require("tests.helper")
local Maid = h.requireModule("core.maid")

h.describe("maid", function()
  h.it("runs function tasks on cleanup", function()
    local m = Maid.new(); local ran = false
    m:Give(function() ran = true end)
    m:DoCleanup()
    h.expect(ran).toBeTruthy()
  end)
  h.it("disconnects connection tasks", function()
    local m = Maid.new(); local disc = false
    m:Give({ Disconnect = function() disc = true end })
    m:DoCleanup()
    h.expect(disc).toBeTruthy()
  end)
  h.it("destroys Instance tasks and clears", function()
    local m = Maid.new()
    local inst = h.roblox.Instance.new("Frame")
    m:Give(inst)
    m:DoCleanup()
    h.expect(inst._destroyed).toBeTruthy()
  end)
  h.it("cleanup is idempotent", function()
    local m = Maid.new(); local n = 0
    m:Give(function() n = n + 1 end)
    m:DoCleanup(); m:DoCleanup()
    h.expect(n).toBe(1)
  end)
end)

h.run()
