local h = require("tests.helper")
local EzUI = h.requireModule("main")

h.describe("main", function()
  h.it("exposes Theme, Icons, NewConfig, CreateWindow", function()
    h.expect(EzUI.Theme ~= nil).toBeTruthy()
    h.expect(EzUI.Icons ~= nil).toBeTruthy()
    h.expect(type(EzUI.NewConfig)).toBe("function")
    h.expect(type(EzUI.CreateWindow)).toBe("function")
  end)
  h.it("CreateWindow returns a window with AddTab", function()
    local screen = h.roblox.Instance.new("ScreenGui")
    local w = EzUI:CreateWindow({ Title = "T", Parent = screen })
    h.expect(type(w.AddTab)).toBe("function")
    local tab = w:AddTab({ Name = "Home" })
    h.expect(tab:IsSelected()).toBe(true)
  end)
end)

h.run()
