local h = require("tests.helper")
local R = h.loadLib()
local NumberBox, Create, Config = R.NumberBox, R.Create, R.Config

h.describe("numberbox", function()
  h.it("clamps to range and persists", function()
    local cfg = Config.new({ FileName = "NB", AutoSave = false })
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "Vol", Default = 50, Min = 0, Max = 100, Flag = "vol", Config = cfg })
    h.expect(nb.GetValue()).toBe(50)
    nb.SetValue(150)
    h.expect(nb.GetValue()).toBe(100)   -- clamped to Max
    h.expect(cfg:Get("vol")).toBe(100)
    nb.SetValue(-5)
    h.expect(nb.GetValue()).toBe(0)     -- clamped to Min
  end)
  h.it("places the box on the right half with Text; Description renders", function()
    local a = NumberBox.new({ Parent = Create("Frame", {}), Text = "Amount", Default = 1 })
    h.expect(a.Frame:FindFirstChild("Box").Position.X.Scale).toBe(0.5)
    local c = NumberBox.new({ Parent = Create("Frame", {}), Text = "Amount", Description = "How many", Default = 1 })
    h.expect(c.Frame:FindFirstChild("Description").Text).toBe("How many")
  end)
  h.it("row has a surface background and the box is bordered", function()
    local nb = NumberBox.new({ Parent = Create("Frame", {}), Text = "Amount", Default = 1 })
    h.expect(nb.Frame.BackgroundTransparency).toBe(0)
    h.expect(nb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke") ~= nil).toBeTruthy()
    local R = h.loadLib()
    h.expect(nb.Frame:FindFirstChild("Box").BackgroundColor3.R8).toBe(R.Theme.Colors.background.R8)
  end)
end)

h.run()
