local h = require("tests.helper")
local numfmt = h.requireModule("core/numfmt")

h.describe("numfmt.format", function()
  local function fmt(n, o) return numfmt.format(n, o) end
  h.it("compact abbreviates with k/M/B/T and strips trailing zeros", function()
    h.expect(fmt(999, { Format = "compact" })).toBe("999")
    h.expect(fmt(1000, { Format = "compact" })).toBe("1k")
    h.expect(fmt(1500, { Format = "compact" })).toBe("1.5k")
    h.expect(fmt(2000, { Format = "compact" })).toBe("2k")
    h.expect(fmt(123456789, { Format = "compact" })).toBe("123.5M")
    h.expect(fmt(72000000000, { Format = "compact" })).toBe("72B")
    h.expect(fmt(4200000000000, { Format = "compact" })).toBe("4.2T")
    h.expect(fmt(-1500, { Format = "compact" })).toBe("-1.5k")
  end)
  h.it("compact honors Decimals", function()
    h.expect(fmt(123456789, { Format = "compact", Decimals = 0 })).toBe("123M")
    h.expect(fmt(1234, { Format = "compact", Decimals = 2 })).toBe("1.23k")
  end)
  h.it("comma groups the integer part", function()
    h.expect(fmt(1234567, { Format = "comma" })).toBe("1,234,567")
    h.expect(fmt(1000, { Format = "comma" })).toBe("1,000")
    h.expect(fmt(100, { Format = "comma" })).toBe("100")
    h.expect(fmt(1234.5, { Format = "comma" })).toBe("1,234.5")
    h.expect(fmt(-1000, { Format = "comma" })).toBe("-1,000")
  end)
  h.it("wraps with Prefix/Suffix and is tostring with no opts", function()
    h.expect(fmt(1500, { Format = "compact", Prefix = "$" })).toBe("$1.5k")
    h.expect(fmt(50, { Suffix = "%" })).toBe("50%")
    h.expect(fmt(42, {})).toBe("42")
    h.expect(fmt(42)).toBe("42")
  end)
end)

h.describe("numfmt.parse", function()
  local function p(s, o) return numfmt.parse(s, o) end
  h.it("parses k/m/b/t case-insensitively", function()
    h.expect(p("1k")).toBe(1000)
    h.expect(p("4.4m")).toBe(4400000)
    h.expect(p("72B")).toBe(72000000000)
    h.expect(p("-1.5k")).toBe(-1500)
  end)
  h.it("strips commas, prefix, suffix", function()
    h.expect(p("1,234")).toBe(1234)
    h.expect(p("$2.5k", { Prefix = "$" })).toBe(2500)
    h.expect(p("50%", { Suffix = "%" })).toBe(50)
    h.expect(p("1500")).toBe(1500)
  end)
  h.it("returns nil for unparseable input", function()
    h.expect(p("abc")).toBeNil()
    h.expect(p("")).toBeNil()
    h.expect(p("k")).toBeNil()
  end)
end)

h.run()
