local h = require("tests.helper")
local Overlay = h.requireModule("core.overlay")
Overlay.reset()

h.describe("overlay", function()
  h.it("creates one root and reuses it", function()
    local gui = h.roblox.Instance.new("ScreenGui")
    local r1 = Overlay.get(gui)
    local r2 = Overlay.get(gui)
    h.expect(r1).toBe(r2)
    h.expect(r1.ClipsDescendants).toBe(false)
  end)
  h.it("mount parents element to overlay root", function()
    local gui = h.roblox.Instance.new("ScreenGui")
    local root = Overlay.get(gui)
    local popup = h.roblox.Instance.new("Frame")
    Overlay.mount(popup)
    h.expect(popup.Parent).toBe(root)
  end)
end)

h.run()
