local h = require("tests.helper")
local R = h.loadLib()
h.describe("playerselector", function()
  h.it("lists current players and updates on PlayerAdded", function()
    local gui = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(gui)
    local ps = R.PlayerSelector.new({ Parent = R.Create("Frame", {}), Text = "Target" })
    h.expect(#ps.GetOptions()).toBe(1)  -- mock has 1 player (Tester)
    local Players = h.roblox.game:GetService("Players")
    table.insert(Players:GetPlayers(), { Name = "Neo", UserId = 2 })
    Players.PlayerAdded:Fire({ Name = "Neo", UserId = 2 })
    h.expect(#ps.GetOptions()).toBe(2)
  end)
end)
h.run()
