local h = require("tests.helper")
local Row = h.requireModule("primitives.row")

h.describe("row", function()
  h.it("builds an auto-sized surface row parented correctly", function()
    local parent = h.roblox.Instance.new("Frame")
    local row = Row.new({ Parent = parent, LayoutOrder = 3 })
    h.expect(row.Frame.Parent).toBe(parent)
    h.expect(row.Frame.AutomaticSize.Name).toBe("Y")
    h.expect(row.Frame.LayoutOrder).toBe(3)
    h.expect(row.Frame.BackgroundColor3.R8).toBe(39)  -- surface
    h.expect(row.Frame:FindFirstChildOfClass("UICorner") ~= nil).toBeTruthy()
  end)
  h.it("SetHovered animates background and Destroy cleans up", function()
    local parent = h.roblox.Instance.new("Frame")
    local row = Row.new({ Parent = parent })
    row.SetHovered(true)
    h.expect(h.mock.lastTween ~= nil).toBeTruthy()
    row.Destroy()
    h.expect(row.Frame._destroyed).toBeTruthy()
  end)
end)

h.run()
