local h = require("tests.helper")
local Tab = h.requireModule("components.tab")
local Create = h.requireModule("core.create")

local function rig()
  return Create("ScrollingFrame", {}), Create("ScrollingFrame", {})
end

h.describe("tab", function()
  h.it("content is a CanvasGroup with UIListLayout + AutomaticSize.Y, hidden by default", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home" })
    h.expect(t.Content.ClassName).toBe("CanvasGroup")
    h.expect(t.Content.AutomaticSize.Name).toBe("Y")
    h.expect(t.Content:FindFirstChildOfClass("UIListLayout") ~= nil).toBeTruthy()
    h.expect(t.Content.Visible).toBe(false)
  end)
  h.it("Select shows + cross-fades GroupTransparency to 0", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    t:Select()
    h.expect(t.Content.Visible).toBe(true)
    h.expect(t:IsSelected()).toBe(true)
    h.expect(t.Content.GroupTransparency).toBe(0)  -- cross-fade tween applied
  end)
  h.it("MountRow parents to content with incrementing order (no Position set)", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    local r = Create("Frame", {})
    local o = t.MountRow(r)
    h.expect(r.Parent).toBe(t.Content)
    h.expect(r.LayoutOrder).toBe(o)
  end)
  h.it("AddAccordion mounts an accordion into content", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    local acc = t:AddAccordion({ Title = "Adv" })
    h.expect(acc.Container.Parent).toBe(t.Content)
  end)
end)

h.run()
