local h = require("tests.helper")
local R = h.loadLib()
local Tab, Create = R.Tab, R.Create

local function rig()
  return Create("ScrollingFrame", {}), Create("ScrollingFrame", {})
end

h.describe("tab", function()
  h.it("content is a Frame with UIListLayout + AutomaticSize.Y, hidden by default", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home" })
    -- a plain Frame (not CanvasGroup) so focused TextBox carets render
    h.expect(t.Content.ClassName).toBe("Frame")
    h.expect(t.Content.AutomaticSize.Name).toBe("Y")
    h.expect(t.Content:FindFirstChildOfClass("UIListLayout") ~= nil).toBeTruthy()
    h.expect(t.Content.Visible).toBe(false)
  end)
  h.it("Select shows + slides the content into place", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    t:Select()
    h.expect(t.Content.Visible).toBe(true)
    h.expect(t:IsSelected()).toBe(true)
    h.expect(t.Content.Position.Y.Offset).toBe(0)  -- slide tween settled at 0
  end)
  h.it("MountRow parents to content with incrementing order (no Position set)", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    local r = Create("Frame", {})
    local o = t.MountRow(r)
    h.expect(r.Parent).toBe(t.Content)
    h.expect(r.LayoutOrder).toBe(o)
  end)
  h.it("AddAccordion mounts an accordion into content", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    local acc = t:AddAccordion({ Title = "Adv" })
    h.expect(acc.Container.Parent).toBe(t.Content)
  end)
  h.it("active indicator sits at the left edge, clear of the icon", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home" })
    h.expect(t.Button:FindFirstChild("Active").Position.X.Offset).toBe(-10)
    h.expect(t.Button:FindFirstChild("Icon").Position.X.Offset).toBe(4)
  end)
end)

h.run()
