local h = require("tests.helper")
local R = h.loadLib()
local Tab, Create = R.Tab, R.Create

local function rig()
  return Create("ScrollingFrame", {}), Create("ScrollingFrame", {})
end

h.describe("tab", function()
  h.it("content is a Frame with UIListLayout + AutomaticSize.Y, hidden by default", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home" })
    -- a plain Frame (not CanvasGroup) so focused TextBox carets render
    h.expect(t.Content.ClassName).toBe("Frame")
    h.expect(t.Content.AutomaticSize.Name).toBe("Y")
    h.expect(t.Content:FindFirstChildOfClass("UIListLayout") ~= nil).toBeTruthy()
    h.expect(t.Content.Visible).toBe(false)
  end)
  h.it("Select shows + slides the content into place and highlights the button", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    t:Select()
    h.expect(t.Content.Visible).toBe(true)
    h.expect(t:IsSelected()).toBe(true)
    h.expect(t.Content.Position.Y.Offset).toBe(0)  -- slide settled at 0
    h.expect(t.Content:FindFirstChildOfClass("UIScale").Scale).toBe(1)  -- scale settled at 1
    h.expect(t.Button.BackgroundTransparency).toBe(0)
  end)
  h.it("Deselect cuts content instantly (no overlapping slide) and resets it", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    t:Select()
    t:Deselect()
    h.expect(t:IsSelected()).toBe(false)
    h.expect(t.Content.Visible).toBe(false)
    h.expect(t.Content.Position.Y.Offset).toBe(0)   -- reset, not left mid-slide
    h.expect(t.Content:FindFirstChildOfClass("UIScale").Scale).toBe(1)
    h.expect(t.Button.BackgroundTransparency).toBe(1)
  end)
  h.it("hovering an unselected tab tints the button, leaving clears it", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    t.Button.MouseEnter:Fire()
    h.expect(t.Button.BackgroundTransparency).toBe(0.92)
    t.Button.MouseLeave:Fire()
    h.expect(t.Button.BackgroundTransparency).toBe(1)
  end)
  h.it("MountRow parents to content with incrementing order (no Position set)", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    local r = Create("Frame", {})
    local o = t.MountRow(r)
    h.expect(r.Parent).toBe(t.Content)
    h.expect(r.LayoutOrder).toBe(o)
  end)
  h.it("AddAccordion mounts an accordion into content", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home" })
    local acc = t:AddAccordion({ Title = "Adv" })
    h.expect(acc.Container.Parent).toBe(t.Content)
  end)
  h.it("no longer creates a per-tab Active indicator (the window owns a shared one now)", function()
    local side, body = rig()
    local t = Tab.new({ SidebarParent = side, ContentParent = body, Name = "Home", Icon = "home" })
    h.expect(t.Button:FindFirstChild("Active")).toBe(nil)
    h.expect(t.Button:FindFirstChild("Icon").Position.X.Offset).toBe(4)  -- icon layout unchanged
  end)
end)

h.run()
