local h = require("tests.helper")
local R = h.loadLib()
h.describe("tab groups + search", function()
  h.it("AddTabGroup adds a header and grouped tabs into the sidebar", function()
    local gui = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(gui)
    local w = R.Window.new({ Title = "W", Parent = gui })
    local g = w:AddTabGroup("Main")
    local t1 = g:AddTab({ Name = "Home" })
    local t2 = g:AddTab({ Name = "Combat" })
    h.expect(t1:IsSelected()).toBe(true)   -- first tab overall auto-selected
    h.expect(t2.Button.Parent).toBe(t1.Button.Parent) -- same sidebar
  end)
  h.it("full-text search filters component rows + their tabs", function()
    local gui = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(gui)
    local w = R.Window.new({ Title = "W", Parent = gui })
    local home = w:AddTab({ Name = "Home" })
    local aim = home:AddToggle({ Text = "Aimbot", Default = false })
    local farm = home:AddToggle({ Text = "Auto Farm", Default = false })
    local combat = w:AddTab({ Name = "Combat" })
    w:SearchTabs("aim")
    h.expect(aim.Frame.Visible).toBe(true)
    h.expect(farm.Frame.Visible).toBe(false)   -- component hidden (no match)
    h.expect(home.Button.Visible).toBe(true)    -- tab kept (has a match)
    h.expect(combat.Button.Visible).toBe(false) -- tab hidden (no name/component match)
    w:SearchTabs("")
    h.expect(farm.Frame.Visible).toBe(true)     -- restored
    h.expect(combat.Button.Visible).toBe(true)
  end)
  h.it("Search hides non-matching tab buttons", function()
    local gui = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(gui)
    local w = R.Window.new({ Title = "W", Parent = gui })
    local home = w:AddTab({ Name = "Home" })
    local combat = w:AddTab({ Name = "Combat" })
    w:SearchTabs("comb")
    h.expect(home.Button.Visible).toBe(false)
    h.expect(combat.Button.Visible).toBe(true)
    w:SearchTabs("")
    h.expect(home.Button.Visible).toBe(true)
  end)
end)
h.run()
