local h = require("tests.helper")
local R = h.loadLib()
local TextBox, Create, Config = R.TextBox, R.Create, R.Config

h.describe("textbox", function()
  h.it("SetText/GetText round-trip and persist", function()
    local cfg = Config.new({ FileName = "TB", AutoSave = false })
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Default = "Player", Flag = "name", Config = cfg })
    h.expect(tb.GetText()).toBe("Player")
    tb.SetText("Neo")
    h.expect(tb.GetText()).toBe("Neo")
    h.expect(cfg:Get("name")).toBe("Neo")
  end)
  h.it("copyable variant exposes a copy button", function()
    local tb = TextBox.new({ Text = "Key", Default = "abc", Copyable = true })
    h.expect(tb.Frame:FindFirstChild("Box"):FindFirstChild("Copy") ~= nil).toBeTruthy()
  end)
  h.it("places the box on the right half when Text is set, full-width without", function()
    local a = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    h.expect(a.Frame:FindFirstChild("Box").Position.X.Scale).toBe(0.5)
    local b = TextBox.new({ Parent = Create("Frame", {}) })
    h.expect(b.Frame:FindFirstChild("Box").Size.X.Scale).toBe(1)
  end)
  h.it("renders a Description when given", function()
    local c = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Description = "Your display name" })
    local d = c.Frame:FindFirstChild("Description")
    h.expect(d ~= nil).toBeTruthy(); h.expect(d.Text).toBe("Your display name")
  end)
  h.it("row has a surface background and the box is bordered", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    h.expect(tb.Frame.BackgroundTransparency).toBe(0)
    h.expect(tb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke") ~= nil).toBeTruthy()
    local R = h.loadLib()
    h.expect(tb.Frame:FindFirstChild("Box").BackgroundColor3.R8).toBe(R.Theme.Colors.background.R8)
  end)
  h.it("box is a horizontal flex row and the input flex-fills", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    local box = tb.Frame:FindFirstChild("Box")
    local layout = box:FindFirstChildOfClass("UIListLayout")
    h.expect(layout ~= nil).toBeTruthy()
    h.expect(layout.FillDirection).toBe(h.roblox.Enum.FillDirection.Horizontal)
    local input = box:FindFirstChild("Input")
    h.expect(input:FindFirstChildOfClass("UIFlexItem").FlexMode).toBe(h.roblox.Enum.UIFlexMode.Fill)
  end)
  h.it("FullWidth stacks the label on top and makes the box full width", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Website", FullWidth = true })
    local box = tb.Frame:FindFirstChild("Box")
    h.expect(box.Size.X.Scale).toBe(1)
    h.expect(box.Position.X.Scale).toBe(0)
    h.expect(tb.Frame:FindFirstChild("Title") ~= nil).toBeTruthy()
  end)
  h.it("renders leading/trailing decorative icons", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Find", LeadingIcon = "search", TrailingIcon = "check" })
    local box = tb.Frame:FindFirstChild("Box")
    h.expect(box:FindFirstChild("LeadingIcon") ~= nil).toBeTruthy()
    h.expect(box:FindFirstChild("LeadingIcon").LayoutOrder).toBe(1)
    h.expect(box:FindFirstChild("TrailingIcon") ~= nil).toBeTruthy()
  end)
  h.it("renders muted prefix and suffix text", function()
    local R = h.loadLib()
    local tb = R.TextBox.new({ Parent = R.Create("Frame", {}), Text = "URL", Prefix = "https://", Suffix = ".com" })
    local box = tb.Frame:FindFirstChild("Box")
    local pre = box:FindFirstChild("Prefix")
    h.expect(pre ~= nil).toBeTruthy()
    h.expect(pre.Text).toBe("https://")
    h.expect(pre.TextColor3.R8).toBe(R.Theme.Colors.mutedForeground.R8)
    h.expect(box:FindFirstChild("Suffix").Text).toBe(".com")
  end)
end)

h.run()
