local h = require("tests.helper")
local R = h.loadLib()
local TextBox, Create, Config = R.TextBox, R.Create, R.Config

h.describe("textbox", function()
  h.it("SetText/GetText round-trip and persist", function()
    local cfg = Config.new({ FileName = "TB", AutoSave = false })
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Default = "Player", Flag = "name", Config = cfg })
    h.expect(tb.GetText()).toBe("Player")
    tb.SetText("Neo")
    h.expect(tb.GetText()).toBe("Neo")
    h.expect(cfg:Get("name")).toBe("Neo")
  end)
  h.it("copyable variant exposes a copy button", function()
    local tb = TextBox.new({ Text = "Key", Default = "abc", Copyable = true })
    h.expect(tb.Frame:FindFirstChild("Box"):FindFirstChild("Copy") ~= nil).toBeTruthy()
  end)
  h.it("places the box on the right half when Text is set, full-width without", function()
    local a = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    h.expect(a.Frame:FindFirstChild("Box").Position.X.Scale).toBe(0.5)
    local b = TextBox.new({ Parent = Create("Frame", {}) })
    h.expect(b.Frame:FindFirstChild("Box").Size.X.Scale).toBe(1)
  end)
  h.it("renders a Description when given", function()
    local c = TextBox.new({ Parent = Create("Frame", {}), Text = "Name", Description = "Your display name" })
    local d = c.Frame:FindFirstChild("Description")
    h.expect(d ~= nil).toBeTruthy(); h.expect(d.Text).toBe("Your display name")
  end)
  h.it("row has a surface background and the box is bordered", function()
    local tb = TextBox.new({ Parent = Create("Frame", {}), Text = "Name" })
    h.expect(tb.Frame.BackgroundTransparency).toBe(0)
    h.expect(tb.Frame:FindFirstChild("Box"):FindFirstChildOfClass("UIStroke") ~= nil).toBeTruthy()
  end)
end)

h.run()
