local h = require("tests.helper")
local R = h.loadLib(); local Themer = R.Themer
h.describe("themer", function()
  h.it("register/unregister/setAccent fires only live appliers", function()
    local t = Themer.new(); local seen = {}
    local off = t.register(function(p, f) seen.p = p; seen.f = f end)
    t.setAccent("P1", "F1"); h.expect(seen.p).toBe("P1"); h.expect(seen.f).toBe("F1")
    off(); t.setAccent("P2", "F2"); h.expect(seen.p).toBe("P1")
  end)
  h.it("ships named accent presets", function()
    h.expect(Themer.accent("Indigo") ~= nil).toBeTruthy()
    h.expect(Themer.accent("Nope")).toBe(nil)
  end)
  h.it("Window:SetAccent recolors a default button live", function()
    local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    local btn = tab:AddButton({ Text = "Go" }) -- default variant
    w:SetAccent("Indigo")
    local ind = Themer.accent("Indigo")
    h.expect(btn.Frame.BackgroundColor3).toBe(ind.Primary)
  end)
  h.it("recolors toggle (on), slider fill, progressbar, and active tab indicator", function()
    local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    local tog = tab:AddToggle({ Text = "t", Default = true })
    local sl = tab:AddSlider({ Text = "s", Min = 0, Max = 10, Default = 5 })
    local pb = tab:AddProgressBar({ Default = 0.5 })
    w:SetAccent("Emerald")
    local em = Themer.accent("Emerald")
    h.expect(tog.Frame:FindFirstChild("Track").BackgroundColor3).toBe(em.Primary)
    h.expect(sl.Frame:FindFirstChild("Track"):FindFirstChild("Fill").BackgroundColor3).toBe(em.Primary)
    h.expect(pb.Frame:FindFirstChild("Track"):FindFirstChild("Fill").BackgroundColor3).toBe(em.Primary)
    h.expect(tab.Button:FindFirstChild("Active").BackgroundColor3).toBe(em.Primary)
  end)
end)
h.run()
