local h = require("tests.helper")
local Theme = h.requireModule("core.theme")

h.describe("theme", function()
  h.it("has exact zinc background", function()
    h.expect(Theme.Colors.background.R8).toBe(9)
    h.expect(Theme.Colors.background.G8).toBe(9)
    h.expect(Theme.Colors.background.B8).toBe(11)
  end)
  h.it("primary is mono white", function()
    h.expect(Theme.Colors.primary.R8).toBe(250)
    h.expect(Theme.Colors.primaryForeground.R8).toBe(24)
  end)
  h.it("radius base-10 scale", function()
    h.expect(Theme.Radius.sm).toBe(6)
    h.expect(Theme.Radius.md).toBe(8)
    h.expect(Theme.Radius.lg).toBe(10)
    h.expect(Theme.Radius.xl).toBe(14)
  end)
  h.it("new() overrides primary without mutating default", function()
    local t = Theme.new({ Colors = { primary = h.roblox.Color3.fromRGB(59,130,246) } })
    h.expect(t.Colors.primary.R8).toBe(59)
    h.expect(Theme.Colors.primary.R8).toBe(250) -- default untouched
    h.expect(t.Colors.background.R8).toBe(9)     -- inherited
  end)
  h.it("ships dark + light palettes", function()
    h.expect(Theme.PALETTES.dark ~= nil).toBeTruthy()
    h.expect(Theme.PALETTES.light ~= nil).toBeTruthy()
  end)
  h.it("applyMode swaps base tokens in place but keeps the accent", function()
    local t = Theme.new()
    t.Colors.primary = h.roblox.Color3.fromRGB(1, 2, 3) -- a custom accent
    Theme.applyMode(t, "light")
    h.expect(t.Colors.background.R8).toBe(250)
    h.expect(t.Colors.foreground.R8).toBe(24)
    h.expect(t.Colors.primary.R8).toBe(1) -- accent preserved
  end)
  h.it("controls recolor on SetMode (text/input backgrounds follow light tokens)", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    local lbl = tab:AddLabel("Hello")
    local tb = tab:AddTextBox({ Text = "Name" })
    local kb = tab:AddKeybind({ Text = "Bind" })
    w:SetMode("light")
    h.expect(lbl.Frame.TextColor3).toBe(R.Theme.PALETTES.light.foreground)
    h.expect(tb.Frame:FindFirstChild("Box").BackgroundColor3).toBe(R.Theme.PALETTES.light.input)
    h.expect(kb.Frame.BackgroundColor3).toBe(R.Theme.PALETTES.light.surface)
  end)
  h.it("accordion lead icon is accent and re-tints on SetMode (not stuck white)", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    local acc = tab:AddAccordion({ Title = "Cfg", Icon = "settings-2" })
    local lead = acc.Header:FindFirstChild("Icon")
    h.expect(lead.ImageColor3.R8).toBe(250)
    w:SetMode("light")
    h.expect(lead.ImageColor3).toBe(R.Theme.PALETTES.light.primary)
    local caret = acc.Header:FindFirstChild("Caret")
    h.expect(caret.ImageColor3).toBe(R.Theme.PALETTES.light.primary)
  end)
  h.it("table rows recolor on SetMode (not stuck dark)", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    local tbl = tab:AddTable({ Columns = { "A", "B" }, Rows = { { "1", "2" } } })
    w:SetMode("light")
    local body = tbl.Frame:FindFirstChild("Body")
    local firstRow; for _, c in ipairs(body:GetChildren()) do if c.Name == "Row" then firstRow = c end end
    h.expect(firstRow.BackgroundColor3).toBe(R.Theme.PALETTES.light.surface)
  end)
  h.it("containers recolor on SetMode (accordion card + divider)", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    local acc = tab:AddAccordion({ Title = "A" })
    w:SetMode("light")
    h.expect(acc.Container.BackgroundColor3).toBe(R.Theme.PALETTES.light.card)
    h.expect(acc.Container:FindFirstChild("Divider").BackgroundColor3).toBe(R.Theme.PALETTES.light.border)
  end)
end)

h.run()
