local h = require("tests.helper")
local Window = h.loadLib().Window

local function newWin()
  local screen = h.roblox.Instance.new("ScreenGui")
  return Window.new({ Title = "My Hub", Parent = screen, Size = { Width = 560, Height = 420 } })
end

h.describe("window", function()
  h.it("builds a gui with a content scroll that auto-sizes its canvas", function()
    local w = newWin()
    h.expect(w.Gui ~= nil).toBeTruthy()
    h.expect(w.ContentScroll.AutomaticCanvasSize.Name).toBe("Y")
  end)
  h.it("first AddTab is auto-selected", function()
    local w = newWin()
    local t1 = w:AddTab({ Name = "Home", Icon = "home" })
    h.expect(t1:IsSelected()).toBe(true)
  end)
  h.it("selecting a second tab deselects the first", function()
    local w = newWin()
    local t1 = w:AddTab({ Name = "A" })
    local t2 = w:AddTab({ Name = "B" })
    h.expect(t1:IsSelected()).toBe(true)
    h.expect(t2:IsSelected()).toBe(false)
    t2.Button.MouseButton1Click:Fire()
    h.expect(t1:IsSelected()).toBe(false)
    h.expect(t2:IsSelected()).toBe(true)
  end)
  h.it("Hide/Show/Toggle flips visibility", function()
    local w = newWin()
    h.expect(w:IsVisible()).toBe(true)
    w:Hide(); h.expect(w:IsVisible()).toBe(false)
    w:Toggle(); h.expect(w:IsVisible()).toBe(true)
  end)
  h.it("FloatingToggle shows a toggle button in the overlay that toggles visibility", function()
    local screen = h.roblox.Instance.new("ScreenGui")
    local R = h.loadLib()
    local w = R.Window.new({ Title = "M", Parent = screen, FloatingToggle = true })
    local root = R.Overlay.get(screen)
    local fab
    for _, c in ipairs(root:GetChildren()) do if c.Name == "FloatingToggle" then fab = c end end
    h.expect(fab ~= nil).toBeTruthy()
    fab.MouseButton1Click:Fire()
    h.expect(w:IsVisible()).toBe(false)
  end)
  h.it("minimize button toggles body visibility", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local minBtn = w.Main:FindFirstChild("TitleBar"):FindFirstChild("Minimize")
    h.expect(minBtn ~= nil).toBeTruthy()
    local body = w.Main:FindFirstChild("Body")
    minBtn.MouseButton1Click:Fire()
    h.expect(body.Visible).toBe(false)
    minBtn.MouseButton1Click:Fire()
    h.expect(body.Visible).toBe(true)
  end)
  h.it("has a resize grip", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    h.expect(w.Main:FindFirstChild("ResizeGrip") ~= nil).toBeTruthy()
  end)
  h.it("Close does a graceful full shutdown", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local fired = {}
    local w = R.Window.new({ Title = "C", Parent = screen, Config = { FileName = "CL", AutoSave = false },
      OnClose = function() fired.onClose = true end })
    w:SetCloseCallback(function() fired.cb = true end)
    local gui = w.Gui
    w:Close()
    h.expect(fired.onClose).toBeTruthy()
    h.expect(fired.cb).toBeTruthy()
    h.expect(gui._destroyed).toBeTruthy()  -- gui torn down
    w:AddTab({ Name = "X" })                -- no-op after close, must not error
    h.expect(w:IsVisible()).toBe(false)
  end)
  h.it("resize grip shows a visible grip icon", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local grip = w.Main:FindFirstChild("ResizeGrip")
    h.expect(tostring(grip.Image):sub(1, 13)).toBe("rbxassetid://")
  end)
  h.it("ToggleKey input toggles visibility", function()
    local w = newWin()
    local uis = h.roblox.game:GetService("UserInputService")
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.RightControl }, false)
    h.expect(w:IsVisible()).toBe(false)
  end)
end)

h.run()
