local h = require("tests.helper")
local Window = h.loadLib().Window

local function newWin()
  local screen = h.roblox.Instance.new("ScreenGui")
  return Window.new({ Title = "My Hub", Parent = screen, Size = { Width = 560, Height = 420 } })
end

h.describe("window", function()
  h.it("builds a gui with a content scroll that auto-sizes its canvas", function()
    local w = newWin()
    h.expect(w.Gui ~= nil).toBeTruthy()
    h.expect(w.ContentScroll.AutomaticCanvasSize.Name).toBe("Y")
  end)
  h.it("first AddTab is auto-selected", function()
    local w = newWin()
    local t1 = w:AddTab({ Name = "Home", Icon = "home" })
    h.expect(t1:IsSelected()).toBe(true)
  end)
  h.it("selecting a second tab deselects the first", function()
    local w = newWin()
    local t1 = w:AddTab({ Name = "A" })
    local t2 = w:AddTab({ Name = "B" })
    h.expect(t1:IsSelected()).toBe(true)
    h.expect(t2:IsSelected()).toBe(false)
    t2.Button.MouseButton1Click:Fire()
    h.expect(t1:IsSelected()).toBe(false)
    h.expect(t2:IsSelected()).toBe(true)
  end)
  h.it("Hide/Show/Toggle flips visibility", function()
    local w = newWin()
    h.expect(w:IsVisible()).toBe(true)
    w:Hide(); h.expect(w:IsVisible()).toBe(false)
    w:Toggle(); h.expect(w:IsVisible()).toBe(true)
  end)
  h.it("FloatingToggle shows a toggle button in the overlay that toggles visibility", function()
    local screen = h.roblox.Instance.new("ScreenGui")
    local R = h.loadLib()
    local w = R.Window.new({ Title = "M", Parent = screen, FloatingToggle = true })
    local root = R.Overlay.get(screen)
    local fab
    for _, c in ipairs(root:GetChildren()) do if c.Name == "FloatingToggle" then fab = c end end
    h.expect(fab ~= nil).toBeTruthy()
    fab.MouseButton1Click:Fire()
    h.expect(w:IsVisible()).toBe(false)
  end)
  h.it("minimize hides the whole window and a floating toggle restores it", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    w:Minimize()
    h.expect(w.Main.Visible).toBe(false)
    h.expect(w:IsVisible()).toBe(false)
    local fab; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then fab = c end end
    h.expect(fab ~= nil).toBeTruthy()
    fab.MouseButton1Click:Fire()
    h.expect(w:IsVisible()).toBe(true)
  end)
  h.it("has a resize grip", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    h.expect(w.Main:FindFirstChild("ResizeGrip") ~= nil).toBeTruthy()
  end)
  h.it("Close does a graceful full shutdown", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local fired = {}
    local w = R.Window.new({ Title = "C", Parent = screen, Config = { FileName = "CL", AutoSave = false },
      OnClose = function() fired.onClose = true end })
    w:SetCloseCallback(function() fired.cb = true end)
    local gui = w.Gui
    w:Close()
    h.expect(fired.onClose).toBeTruthy()
    h.expect(fired.cb).toBeTruthy()
    h.expect(gui._destroyed).toBeTruthy()  -- gui torn down
    w:AddTab({ Name = "X" })                -- no-op after close, must not error
    h.expect(w:IsVisible()).toBe(false)
  end)
  h.it("sidebar handle resizes the sidebar width", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local body = w.Main:FindFirstChild("Body")
    local handle = body:FindFirstChild("SidebarHandle")
    h.expect(handle ~= nil).toBeTruthy()
    local sidebar = body:FindFirstChild("Sidebar")
    local w0 = sidebar.Size.X.Offset
    body.AbsolutePosition = h.roblox.Vector2.new(0, 0)
    handle.InputBegan:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseButton1, Position = h.roblox.Vector2.new(w0, 50) })
    local uis = h.roblox.game:GetService("UserInputService")
    uis.InputChanged:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseMovement, Position = h.roblox.Vector2.new(w0 + 40, 50) })
    h.expect(sidebar.Size.X.Offset > w0).toBeTruthy()
  end)
  h.it("settings APIs: notifications gate, UI scale, acrylic transparency, toggle key", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    R.Notification.clearAll()
    w:SetNotificationsEnabled(false)
    h.expect(w:Notify({ Title = "x", Duration = 0 })).toBe(nil)
    h.expect(R.Notification.count()).toBe(0)
    w:SetNotificationsEnabled(true)
    w:SetUIScale(1.2)
    local sc = w.Main:FindFirstChildOfClass("UIScale")
    h.expect(sc ~= nil).toBeTruthy(); h.expect(sc.Scale).toBe(1.2)
    w:SetAcrylicTransparency(0.5)
    h.expect(w.Main.BackgroundTransparency).toBe(0.5)
    h.expect(w:SetToggleKey(h.roblox.Enum.KeyCode.K)).toBe(h.roblox.Enum.KeyCode.K)
  end)
  h.it("closes an open popover when switching tabs", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); local ov = R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local t1 = w:AddTab({ Name = "One" }); local t2 = w:AddTab({ Name = "Two" })
    local sb = t1:AddSelectBox({ Text = "S", Options = { "a", "b" } })
    sb.Open()
    local hasDrop = false; for _, c in ipairs(ov:GetChildren()) do if c.Name == "SelectDropdown" then hasDrop = true end end
    h.expect(hasDrop).toBe(true)
    t2.Button.MouseButton1Click:Fire()
    local stillOpen = false; for _, c in ipairs(ov:GetChildren()) do if c.Name == "SelectDropdown" then stillOpen = true end end
    h.expect(stillOpen).toBe(false)
  end)
  h.it("defaults the floating toggle to the simple type", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen, FloatingToggle = true })
    local fab; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then fab = c end end
    h.expect(fab ~= nil).toBeTruthy()
    h.expect(fab:GetAttribute("FabType")).toBe("simple")
  end)
  h.it("square floating toggle renders the given image and SetFloatingToggle swaps type", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen,
      FloatingToggle = { Type = "square", Image = "rbxassetid://123", Draggable = false } })
    local fab; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then fab = c end end
    local img = fab:FindFirstChildOfClass("ImageLabel")
    h.expect(img.Image).toBe("rbxassetid://123")
    w:SetFloatingToggle({ Type = "simple" })
    local fab2; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then fab2 = c end end
    h.expect(fab2:GetAttribute("FabType")).toBe("simple")
    w:Minimize()
    fab2.MouseButton1Click:Fire()
    h.expect(w:IsVisible()).toBe(true)
  end)
  h.it("Window:Tag adds a topbar pill that can be removed", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tag = w:Tag({ Text = "Beta" })
    local tb = w.Main:FindFirstChild("TitleBar")
    local pill; for _, c in ipairs(tb:GetChildren()) do if c.Name == "Tag" then pill = c end end
    h.expect(pill ~= nil).toBeTruthy()
    h.expect(pill:FindFirstChild("TagText").Text).toBe("Beta")
    tag.Destroy()
    local gone = true; for _, c in ipairs(tb:GetChildren()) do if c.Name == "Tag" then gone = false end end
    h.expect(gone).toBe(true)
  end)
  h.it("has a header separator at the title-bar seam", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local sep = w.Main:FindFirstChild("HeaderSeparator")
    h.expect(sep ~= nil).toBeTruthy()
    h.expect(sep.Position.Y.Offset).toBe(40) -- TITLE_H
  end)
  h.it("resize grip shows a visible grip icon", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local grip = w.Main:FindFirstChild("ResizeGrip")
    h.expect(tostring(grip.Image):sub(1, 13)).toBe("rbxassetid://")
  end)
  h.it("ToggleKey input toggles visibility", function()
    local w = newWin()
    local uis = h.roblox.game:GetService("UserInputService")
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.RightControl }, false)
    h.expect(w:IsVisible()).toBe(false)
  end)
end)

h.run()
