local h = require("tests.helper")
local Window = h.loadLib().Window

local function newWin()
  local screen = h.roblox.Instance.new("ScreenGui")
  return Window.new({ Title = "My Hub", Parent = screen })
end

h.describe("window", function()
  h.it("builds a gui with a content scroll (CanvasSize driven explicitly per tab)", function()
    local w = newWin()
    h.expect(w.Gui ~= nil).toBeTruthy()
    h.expect(w.ContentScroll.AutomaticCanvasSize.Name).toBe("None")
  end)
  h.it("first AddTab is auto-selected", function()
    local w = newWin()
    local t1 = w:AddTab({ Name = "Home", Icon = "home" })
    h.expect(t1:IsSelected()).toBe(true)
  end)
  h.it("selecting a second tab deselects the first", function()
    local w = newWin()
    local t1 = w:AddTab({ Name = "A" })
    local t2 = w:AddTab({ Name = "B" })
    h.expect(t1:IsSelected()).toBe(true)
    h.expect(t2:IsSelected()).toBe(false)
    t2.Button.MouseButton1Click:Fire()
    h.expect(t1:IsSelected()).toBe(false)
    h.expect(t2:IsSelected()).toBe(true)
  end)
  h.it("Hide/Show/Toggle flips visibility", function()
    local w = newWin()
    h.expect(w:IsVisible()).toBe(true)
    w:Hide(); h.expect(w:IsVisible()).toBe(false)
    w:Toggle(); h.expect(w:IsVisible()).toBe(true)
  end)
  h.it("FAB is the reopen button: hidden when shown, appears on hide, no shadow, tap restores", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen, FloatingToggle = true })
    local function findFab() for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then return c end end end
    local fab = findFab()
    h.expect(fab ~= nil).toBeTruthy()
    h.expect(fab.Visible).toBe(false)
    h.expect(fab:GetAttribute("FabType")).toBe("simple")
    h.expect(fab:FindFirstChild("Chevron") ~= nil).toBeTruthy()
    local shadow; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggleShadow" then shadow = c end end
    h.expect(shadow).toBe(nil)
    w:Hide()
    h.expect(findFab().Visible).toBe(true)
    w:Show()
    h.expect(findFab().Visible).toBe(false)
    w:Minimize()
    h.expect(findFab().Visible).toBe(true)
    findFab().MouseButton1Click:Fire()
    h.expect(w:IsVisible()).toBe(true)
  end)
  h.it("minimize hides the whole window and a floating toggle restores it", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    w:Minimize()
    h.expect(w.Main.Visible).toBe(false)
    h.expect(w:IsVisible()).toBe(false)
    local fab; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then fab = c end end
    h.expect(fab ~= nil).toBeTruthy()
    fab.MouseButton1Click:Fire()
    h.expect(w:IsVisible()).toBe(true)
  end)
  h.it("has a resize grip", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    h.expect(w.Main:FindFirstChild("ResizeGrip") ~= nil).toBeTruthy()
  end)
  h.it("Close does a graceful full shutdown", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local fired = {}
    local w = R.Window.new({ Title = "C", Parent = screen, Config = { FileName = "CL", AutoSave = false },
      OnClose = function() fired.onClose = true end })
    w:SetCloseCallback(function() fired.cb = true end)
    local gui = w.Gui
    w:Close()
    h.expect(fired.onClose).toBeTruthy()
    h.expect(fired.cb).toBeTruthy()
    h.expect(gui._destroyed).toBeTruthy()  -- gui torn down
    w:AddTab({ Name = "X" })                -- no-op after close, must not error
    h.expect(w:IsVisible()).toBe(false)
  end)
  h.it("SaveConfiguration / LoadConfiguration delegate to the config object", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen, Config = { FileName = "WCfg", AutoSave = false } })
    local tab = w:AddTab({ Name = "T" })
    tab:AddToggle({ Text = "x", Flag = "x", Default = true })
    h.expect(w:SaveConfiguration()).toBeTruthy()
    h.expect(type(w:LoadConfiguration())).toBe("boolean")
  end)
  h.it("light mode re-skins the acrylic gradient + stroke to light tokens", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    w:SetMode("light")
    local grad = w.Main:FindFirstChildOfClass("UIGradient")
    local stroke = w.Main:FindFirstChildOfClass("UIStroke")
    h.expect(grad.Color.color[1].Value).toBe(R.Theme.PALETTES.light.card)  -- gradient top now card (chrome darker)
    h.expect(stroke.Color).toBe(R.Theme.PALETTES.light.border)
  end)
  h.it("sidebar handle resizes the sidebar width", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local body = w.Main:FindFirstChild("Body")
    local handle = body:FindFirstChild("SidebarHandle")
    h.expect(handle ~= nil).toBeTruthy()
    local sidebar = body:FindFirstChild("Sidebar")
    local w0 = sidebar.Size.X.Offset
    body.AbsolutePosition = h.roblox.Vector2.new(0, 0)
    handle.InputBegan:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseButton1, Position = h.roblox.Vector2.new(w0, 50) })
    local uis = h.roblox.game:GetService("UserInputService")
    uis.InputChanged:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseMovement, Position = h.roblox.Vector2.new(w0 + 40, 50) })
    h.expect(sidebar.Size.X.Offset > w0).toBeTruthy()
  end)
  h.it("settings APIs: notifications gate, UI scale, acrylic transparency, toggle key", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    R.Notification.clearAll()
    w:SetNotificationsEnabled(false)
    h.expect(w:Notify({ Title = "x", Duration = 0 })).toBe(nil)
    h.expect(R.Notification.count()).toBe(0)
    w:SetNotificationsEnabled(true)
    w:SetUIScale(1.2)
    local sc = w.Main:FindFirstChildOfClass("UIScale")
    h.expect(sc ~= nil).toBeTruthy(); h.expect(sc.Scale).toBe(1.2)
    w:SetTransparency(0.5)
    h.expect(w.Main.BackgroundTransparency).toBe(0.5)
    h.expect(w:SetToggleKey(h.roblox.Enum.KeyCode.K)).toBe(h.roblox.Enum.KeyCode.K)
  end)
  h.it("closes an open popover when switching tabs", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); local ov = R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local t1 = w:AddTab({ Name = "One" }); local t2 = w:AddTab({ Name = "Two" })
    local sb = t1:AddSelectBox({ Text = "S", Options = { "a", "b" } })
    sb.Open()
    local hasDrop = false; for _, c in ipairs(ov:GetChildren()) do if c.Name == "SelectDropdown" then hasDrop = true end end
    h.expect(hasDrop).toBe(true)
    t2.Button.MouseButton1Click:Fire()
    local stillOpen = false; for _, c in ipairs(ov:GetChildren()) do if c.Name == "SelectDropdown" then stillOpen = true end end
    h.expect(stillOpen).toBe(false)
  end)
  h.it("floating toggle honors Size and Position overrides", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen, FloatingToggle = { Type = "circle" } })
    w:SetFloatingToggle({ Type = "circle", Size = h.roblox.UDim2.new(0, 150, 0, 40), Position = h.roblox.UDim2.new(0, 30, 1, -80) })
    local fab; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then fab = c end end
    h.expect(fab.Size.X.Offset).toBe(150)
    h.expect(fab.Size.Y.Offset).toBe(40)
    h.expect(fab.Position.X.Offset).toBe(30)
    h.expect(fab.Position.Y.Offset).toBe(-80)
  end)
  h.it("simple floating toggle docks at the left edge (magnet)", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen, FloatingToggle = true })
    local fab; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then fab = c end end
    h.expect(fab.Position.X.Offset).toBe(-15)
    h.expect(fab.Position.Y.Scale).toBe(0.5)
  end)
  h.it("FAB chevron + title-bar icons are accent and follow the mode", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen, FloatingToggle = true })
    local fab; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then fab = c end end
    h.expect(fab:FindFirstChild("Chevron").ImageColor3.R8).toBe(250)
    local close = w.Main:FindFirstChild("TitleBar"):FindFirstChild("Close")
    h.expect(close.ImageColor3.R8).toBe(R.Theme.Colors.mutedForeground.R8)  -- topbar icons rest neutral now
    w:SetMode("light")
    h.expect(fab:FindFirstChild("Chevron").ImageColor3).toBe(R.Theme.PALETTES.light.primary)
    h.expect(close.ImageColor3).toBe(R.Theme.PALETTES.light.mutedForeground)
  end)
  h.it("magnet snaps to the correct edge using logical position (slow-drag safe)", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui")
    local ov = R.Overlay.get(screen); ov.AbsoluteSize = h.roblox.Vector2.new(600, 400)
    local w = R.Window.new({ Title = "M", Parent = screen, FloatingToggle = true })
    local fab; for _, c in ipairs(ov:GetChildren()) do if c.Name == "FloatingToggle" then fab = c end end
    local uis = h.roblox.game:GetService("UserInputService")
    fab.InputBegan:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseButton1, Position = h.roblox.Vector2.new(0, 0) })
    uis.InputChanged:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseMovement, Position = h.roblox.Vector2.new(400, 0) })
    uis.InputEnded:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseButton1, Position = h.roblox.Vector2.new(400, 0) })
    h.expect(fab.Position.X.Offset > 300).toBeTruthy()
    fab.InputBegan:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseButton1, Position = h.roblox.Vector2.new(0, 0) })
    uis.InputChanged:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseMovement, Position = h.roblox.Vector2.new(-500, 0) })
    uis.InputEnded:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseButton1, Position = h.roblox.Vector2.new(-500, 0) })
    h.expect(fab.Position.X.Offset).toBe(-15)
  end)
  h.it("simple FAB uses a neutral surface color that follows the mode", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen, FloatingToggle = true })
    local fab; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then fab = c end end
    -- compare by value: the window deep-copies its theme (distinct Color3 identity from the module)
    h.expect(fab.BackgroundColor3.R8).toBe(R.Theme.PALETTES.dark.surface.R8)        -- 39 (not white primary)
    h.expect(fab:FindFirstChild("Chevron").ImageColor3.R8).toBe(R.Theme.PALETTES.dark.foreground.R8) -- 250
    w:SetMode("light")
    h.expect(fab.BackgroundColor3.R8).toBe(R.Theme.PALETTES.light.surface.R8)        -- 244 (follows mode)
  end)
  h.it("square floating toggle renders the given image and SetFloatingToggle swaps type", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen,
      FloatingToggle = { Type = "square", Image = "rbxassetid://123", Draggable = false } })
    local fab; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then fab = c end end
    local img = fab:FindFirstChildOfClass("ImageLabel")
    h.expect(img.Image).toBe("rbxassetid://123")
    w:SetFloatingToggle({ Type = "simple" })
    local fab2; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then fab2 = c end end
    h.expect(fab2:GetAttribute("FabType")).toBe("simple")
    w:Minimize()
    fab2.MouseButton1Click:Fire()
    h.expect(w:IsVisible()).toBe(true)
  end)
  h.it("SetAccent(Color3) picks a readable foreground by luminance", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" }); local b = tab:AddButton({ Text = "Go" })
    w:SetAccent(h.roblox.Color3.fromRGB(255, 255, 255))
    h.expect(b.Frame:FindFirstChild("Surface"):FindFirstChild("Label").TextColor3.R8).toBe(24)
    w:SetAccent(h.roblox.Color3.fromRGB(20, 20, 20))
    h.expect(b.Frame:FindFirstChild("Surface"):FindFirstChild("Label").TextColor3.R8).toBe(250)
  end)
  h.it("SetAccent accepts a preset name (used by the Settings accent selector)", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    local b = tab:AddButton({ Text = "Go" })
    w:SetAccent("Emerald")
    h.expect(b.Frame:FindFirstChild("Surface").BackgroundColor3).toBe(R.Themer.accent("Emerald").Primary)
  end)
  h.it("topbar tag recolors on SetMode", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tag = w:Tag({ Text = "Beta" })
    w:SetMode("light")
    local tb = w.Main:FindFirstChild("TitleBar")
    local pill; for _, c in ipairs(tb:GetChildren()) do if c.Name == "Tag" then pill = c end end
    h.expect(pill.BackgroundColor3).toBe(R.Theme.PALETTES.light.surface)
    h.expect(pill:FindFirstChild("TagText").TextColor3).toBe(R.Theme.PALETTES.light.foreground)
  end)
  h.it("Window:Tag adds a topbar pill that can be removed", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tag = w:Tag({ Text = "Beta" })
    local tb = w.Main:FindFirstChild("TitleBar")
    local pill; for _, c in ipairs(tb:GetChildren()) do if c.Name == "Tag" then pill = c end end
    h.expect(pill ~= nil).toBeTruthy()
    h.expect(pill:FindFirstChild("TagText").Text).toBe("Beta")
    tag.Destroy()
    local gone = true; for _, c in ipairs(tb:GetChildren()) do if c.Name == "Tag" then gone = false end end
    h.expect(gone).toBe(true)
  end)
  h.it("resize grip shows a visible grip icon", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local grip = w.Main:FindFirstChild("ResizeGrip")
    h.expect(tostring(grip.Image):sub(1, 13)).toBe("rbxassetid://")
  end)
  h.it("ToggleKey input toggles visibility", function()
    local w = newWin()
    local uis = h.roblox.game:GetService("UserInputService")
    uis.InputBegan:Fire({ KeyCode = h.roblox.Enum.KeyCode.RightControl }, false)
    h.expect(w:IsVisible()).toBe(false)
  end)
  h.it("flat chrome: darker base, rounded card content panel, no separators", function()
    local R = h.loadLib()
    local w = newWin()
    h.expect(w.Main:FindFirstChild("HeaderSeparator")).toBe(nil)
    h.expect(w.Main:FindFirstChild("HeaderShadow")).toBe(nil)
    h.expect(w.Main.BackgroundColor3.R8).toBe(R.Theme.Colors.background.R8)
    local body = w.Main:FindFirstChild("Body")
    local panel = body:FindFirstChild("ContentPanel")
    h.expect(panel ~= nil).toBeTruthy()
    h.expect(panel.BackgroundColor3.R8).toBe(R.Theme.Colors.card.R8)
    h.expect(w.ContentScroll.Parent.Name).toBe("ContentPanel")
  end)
  h.it("close button asks for confirmation by default; ConfirmClose=false closes immediately", function()
    local R = h.loadLib()
    local screen = h.roblox.Instance.new("ScreenGui"); local ov = R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local close = w.Main:FindFirstChild("TitleBar"):FindFirstChild("Close")
    close.MouseButton1Click:Fire()
    h.expect(ov:FindFirstChild("Dialog") ~= nil).toBeTruthy()
    h.expect(w:IsVisible()).toBe(true)
    local screen2 = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen2)
    local w2 = R.Window.new({ Title = "M2", Parent = screen2, ConfirmClose = false })
    w2.Main:FindFirstChild("TitleBar"):FindFirstChild("Close").MouseButton1Click:Fire()
    h.expect(w2:IsVisible()).toBe(false)
  end)
  h.it("content scroll uses explicit CanvasSize driven by the active tab", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local tab = w:AddTab({ Name = "T" })
    tab:AddParagraph("hello"); tab:AddButton({ Text = "Go" })
    tab:Select()
    h.expect(w.ContentScroll.AutomaticCanvasSize.Name).toBe("None")
    h.expect(w.ContentScroll.CanvasSize.Y.Offset).toBe(2 * R.Theme.Spacing.pad)
  end)
  h.it("topbar minimize/close icons rest neutral and colour on hover", function()
    local R = h.loadLib()
    local w = newWin()
    local bar = w.Main:FindFirstChild("TitleBar")
    local close = bar:FindFirstChild("Close")
    local mn = bar:FindFirstChild("Minimize")
    h.expect(close.ImageColor3.R8).toBe(R.Theme.Colors.mutedForeground.R8)
    close.MouseEnter:Fire(); h.expect(close.ImageColor3.R8).toBe(R.Theme.Colors.destructive.R8)
    close.MouseLeave:Fire(); h.expect(close.ImageColor3.R8).toBe(R.Theme.Colors.mutedForeground.R8)
    mn.MouseEnter:Fire(); h.expect(mn.ImageColor3.R8).toBe(R.Theme.Colors.primary.R8)
    mn.MouseLeave:Fire(); h.expect(mn.ImageColor3.R8).toBe(R.Theme.Colors.mutedForeground.R8)
  end)
  h.it("Transparency sets the window background and keeps the frosted stack", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen, Transparency = 0.3 })
    h.expect(w.Main.BackgroundTransparency).toBe(0.3)
    h.expect(w.Main:FindFirstChild("AcrylicNoise") ~= nil).toBeTruthy()  -- frosted always on
    h.expect(w:SetTransparency(0.5)).toBe(0.5)
    h.expect(w.Main.BackgroundTransparency).toBe(0.5)
  end)
  h.it("Ratio sets the window shape: square => equal sides, default ~= 4:3", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local sq = R.Window.new({ Title = "M", Parent = screen, Ratio = 1 })
    h.expect(sq.Main.Size.X.Offset).toBe(sq.Main.Size.Y.Offset)         -- 1:1
    local def = R.Window.new({ Title = "M", Parent = screen })          -- default 4/3
    local r = def.Main.Size.X.Offset / def.Main.Size.Y.Offset
    h.expect(r > 1.2 and r < 1.45).toBeTruthy()
  end)
  h.it("Subtitle + Image build a taller (56px) title bar with both slots", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "Hub", Subtitle = "v3.0", Image = "rbxassetid://42", Parent = screen })
    local bar = w.Main:FindFirstChild("TitleBar")
    h.expect(bar.Size.Y.Offset).toBe(56)
    h.expect(bar:FindFirstChild("TitleImage").Image).toBe("rbxassetid://42")
    h.expect(bar:FindFirstChild("Subtitle").Text).toBe("v3.0")
    w:SetSubtitle("v3.1")
    h.expect(bar:FindFirstChild("Subtitle").Text).toBe("v3.1")
  end)
  h.it("plain title keeps the 40px bar with no subtitle/image slots", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "Hub", Parent = screen })
    local bar = w.Main:FindFirstChild("TitleBar")
    h.expect(bar.Size.Y.Offset).toBe(40)
    h.expect(bar:FindFirstChild("Subtitle")).toBe(nil)
    h.expect(bar:FindFirstChild("TitleImage")).toBe(nil)
  end)
  h.it("FloatingToggle AutoHide=false keeps the FAB visible while the window is shown", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen, FloatingToggle = { AutoHide = false } })
    local function findFab() for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then return c end end end
    h.expect(findFab().Visible).toBe(true)           -- visible even though the window is shown
    w:Hide()
    h.expect(findFab().Visible).toBe(true)
    findFab().MouseButton1Click:Fire()               -- toggles back open
    h.expect(w:IsVisible()).toBe(true)
  end)
  h.it("FloatingToggle=false disables the FAB entirely", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen, FloatingToggle = false })
    local function findFab() for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then return c end end end
    h.expect(findFab()).toBe(nil)
    w:Hide()                                          -- must not create/restore a FAB
    h.expect(findFab()).toBe(nil)
    h.expect(w:IsVisible()).toBe(false)
  end)
  h.it("AdaptToViewport keeps a user-moved window's position but re-centers an untouched one", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "M", Parent = screen })
    local bar = w.Main:FindFirstChild("TitleBar")
    local uis = h.roblox.game:GetService("UserInputService")
    bar.InputBegan:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseButton1, Position = h.roblox.Vector2.new(100, 10) })
    uis.InputChanged:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseMovement, Position = h.roblox.Vector2.new(140, 30) })
    bar.InputEnded:Fire({ UserInputType = h.roblox.Enum.UserInputType.MouseButton1, Position = h.roblox.Vector2.new(140, 30) })
    w:AdaptToViewport()
    h.expect(w.Main.Position.X.Scale).toBe(0)   -- user-moved: clamped pure-offset position, not re-centered
    h.expect(w.Main.Position.Y.Scale).toBe(0)
    local w2 = R.Window.new({ Title = "M", Parent = screen })
    w2:AdaptToViewport()
    h.expect(w2.Main.Position.X.Scale).toBe(0.5) -- untouched window still re-centers
  end)
  h.it("SetImage updates the title-bar image", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local w = R.Window.new({ Title = "Hub", Image = "rbxassetid://42", Parent = screen })
    local bar = w.Main:FindFirstChild("TitleBar")
    w:SetImage("rbxassetid://99")
    h.expect(bar:FindFirstChild("TitleImage").Image).toBe("rbxassetid://99")
  end)
  h.it("FloatingToggle simple Position docks as a tab (default MidLeft, MidRight on the right)", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local function lastFab() local r; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then r = c end end return r end
    R.Window.new({ Title = "M", Parent = screen, FloatingToggle = { Type = "simple" } })
    local def = lastFab()
    h.expect(def.Position.X.Offset).toBe(-15); h.expect(def.Position.Y.Scale).toBe(0.5)  -- default MidLeft tab
    R.Window.new({ Title = "M", Parent = screen, FloatingToggle = { Type = "simple", Position = "MidRight" } })
    local mr = lastFab()
    h.expect(mr.Position.X.Scale).toBe(1); h.expect(mr.Position.Y.Scale).toBe(0.5)        -- right-edge tab
  end)
  h.it("FloatingToggle circle Position anchors fully visible (default TopLeft, BottomRight)", function()
    local R = h.loadLib(); local screen = h.roblox.Instance.new("ScreenGui"); R.Overlay.get(screen)
    local function lastFab() local r; for _, c in ipairs(R.Overlay.get(screen):GetChildren()) do if c.Name == "FloatingToggle" then r = c end end return r end
    R.Window.new({ Title = "M", Parent = screen, FloatingToggle = { Type = "circle" } })
    local def = lastFab()
    h.expect(def.Position.X.Scale).toBe(0); h.expect(def.Position.X.Offset).toBe(16)       -- default TopLeft, fully visible
    h.expect(def.Position.Y.Scale).toBe(0); h.expect(def.Position.Y.Offset).toBe(16)
    R.Window.new({ Title = "M", Parent = screen, FloatingToggle = { Type = "circle", Position = "BottomRight" } })
    local br = lastFab()
    h.expect(br.Position.X.Scale).toBe(1); h.expect(br.Position.X.Offset).toBe(-60)        -- 44 + 16 margin
    h.expect(br.Position.Y.Scale).toBe(1); h.expect(br.Position.Y.Offset).toBe(-60)
  end)
end)

h.run()
