-- AUTO-GENERATED by scripts/build-icons.mjs from latte-soft/lucide-roblox (ISC/MIT).
-- Curated subset; edit scripts/icons.manifest.txt then run `make icons`.
local DATA = {
  ["home"] = { id = 16898613509, w = 48, h = 48, x = 820, y = 147 },
  ["settings"] = { id = 16898613777, w = 48, h = 48, x = 771, y = 257 },
  ["settings-2"] = { id = 16898613777, w = 48, h = 48, x = 0, y = 771 },
  ["target"] = { id = 16898613869, w = 48, h = 48, x = 514, y = 771 },
  ["chevron-right"] = { id = 16898612819, w = 48, h = 48, x = 869, y = 759 },
  ["chevron-down"] = { id = 16898612819, w = 48, h = 48, x = 196, y = 918 },
  ["chevron-left"] = { id = 16898612819, w = 48, h = 48, x = 404, y = 967 },
  ["chevron-up"] = { id = 16898612819, w = 48, h = 48, x = 710, y = 918 },
  ["play"] = { id = 16898613699, w = 48, h = 48, x = 918, y = 257 },
  ["pause"] = { id = 16898613699, w = 48, h = 48, x = 0, y = 771 },
  ["x"] = { id = 16898613869, w = 48, h = 48, x = 869, y = 906 },
  ["search"] = { id = 16898613699, w = 48, h = 48, x = 918, y = 857 },
  ["user"] = { id = 16898613869, w = 48, h = 48, x = 661, y = 869 },
  ["users"] = { id = 16898613869, w = 48, h = 48, x = 967, y = 98 },
  ["check"] = { id = 16898612819, w = 48, h = 48, x = 710, y = 869 },
  ["plus"] = { id = 16898613699, w = 48, h = 48, x = 257, y = 918 },
  ["minus"] = { id = 16898613613, w = 48, h = 48, x = 771, y = 196 },
  ["copy"] = { id = 16898613044, w = 48, h = 48, x = 918, y = 612 },
  ["trash-2"] = { id = 16898613869, w = 48, h = 48, x = 257, y = 918 },
  ["eye"] = { id = 16898613353, w = 48, h = 48, x = 771, y = 563 },
  ["eye-off"] = { id = 16898613353, w = 48, h = 48, x = 820, y = 514 },
  ["lock"] = { id = 16898613509, w = 48, h = 48, x = 918, y = 857 },
  ["unlock"] = { id = 16898613869, w = 48, h = 48, x = 771, y = 710 },
  ["zap"] = { id = 16898613869, w = 48, h = 48, x = 918, y = 906 },
  ["swords"] = { id = 16898613777, w = 48, h = 48, x = 967, y = 759 },
  ["crosshair"] = { id = 16898613044, w = 48, h = 48, x = 453, y = 869 },
  ["map-pin"] = { id = 16898613613, w = 48, h = 48, x = 820, y = 257 },
  ["bell"] = { id = 16898612819, w = 48, h = 48, x = 820, y = 257 },
  ["star"] = { id = 16898613777, w = 48, h = 48, x = 967, y = 147 },
  ["heart"] = { id = 16898613509, w = 48, h = 48, x = 661, y = 771 },
  ["shield"] = { id = 16898613777, w = 48, h = 48, x = 869, y = 0 },
  ["gamepad-2"] = { id = 16898613353, w = 48, h = 48, x = 710, y = 967 },
  ["sliders-horizontal"] = { id = 16898613777, w = 48, h = 48, x = 820, y = 355 },
  ["toggle-left"] = { id = 16898613869, w = 48, h = 48, x = 869, y = 49 },
  ["palette"] = { id = 16898613613, w = 48, h = 48, x = 453, y = 918 },
  ["info"] = { id = 16898613509, w = 48, h = 48, x = 612, y = 869 },
  ["circle-alert"] = { id = 16898612819, w = 48, h = 48, x = 918, y = 808 },
  ["circle-check"] = { id = 16898612819, w = 48, h = 48, x = 869, y = 955 },
  ["triangle-alert"] = { id = 16898613869, w = 48, h = 48, x = 967, y = 0 },
  ["loader"] = { id = 16898613509, w = 48, h = 48, x = 710, y = 967 },
  ["refresh-cw"] = { id = 16898613699, w = 48, h = 48, x = 404, y = 869 },
  ["power"] = { id = 16898613699, w = 48, h = 48, x = 820, y = 147 },
}

local Icons = { data = DATA }

-- Name aliases: this lucide port predates upstream renames. Keep shadcn-current
-- names working (e.g. "house" → "home"). Lives below the generator's marker so
-- `make icons` regeneration preserves it.
local ALIAS = {
  house = "home",
}

function Icons.get(name)
  local e = DATA[name] or DATA[ALIAS[name] or ""]
  if not e then return nil end
  return {
    Id = "rbxassetid://" .. e.id,
    ImageRectSize = Vector2.new(e.w, e.h),
    ImageRectOffset = Vector2.new(e.x, e.y),
  }
end

function Icons.apply(imageLabel, name, color3)
  local a = Icons.get(name)
  if not a then
    if warn then warn("[EzUI] unknown icon: " .. tostring(name)) end
    return false
  end
  imageLabel.Image = a.Id
  imageLabel.ImageRectSize = a.ImageRectSize
  imageLabel.ImageRectOffset = a.ImageRectOffset
  if color3 then imageLabel.ImageColor3 = color3 end
  return true
end

return Icons
