return function(window, host)
  host = host or window
  local tab = host:AddTab({ Name = "PlayerSelector", Icon = "users" })
  tab:AddSection("Basic")
  tab:AddPlayerSelector({ Text = "Target" })
  tab:AddPlayerSelector({ Text = "Targets", Multi = true })
  tab:AddPlayerSelector({ Text = "With description", Description = "Pick a player in the server." })
  tab:AddSection("Persistence (Flag)")
  tab:AddPlayerSelector({ Text = "Saved target", Flag = "ex_player" })
  tab:AddParagraph("Auto-updates as players join/leave; Flag-bound selectors auto-save and restore.")
  local acc = tab:AddAccordion({ Title = "Inside an accordion", Icon = "rows-3", Expanded = false })
  acc:AddPlayerSelector({ Text = "Nested" })
  local acc2 = tab:AddAccordion({ Title = "Expanded by default", Icon = "rows-3", Expanded = true })
  acc2:AddPlayerSelector({ Text = "Nested" })
end
