return function(window, host)
  host = host or window
  local tab = host:AddTab({ Name = "TextBox", Icon = "type" })
  tab:AddSection("Basic")
  tab:AddTextBox({ Text = "Name", Placeholder = "Type your name…" })
  tab:AddTextBox({ Text = "With description", Description = "Helper text under the label.", Placeholder = "…" })
  tab:AddTextBox({ Text = "Key", Default = "EZUI-DEMO", Copyable = true })
  tab:AddSection("Persistence (Flag)")
  tab:AddTextBox({ Text = "Saved note", Flag = "ex_textbox", Default = "hello" })
  tab:AddParagraph("Flag-bound controls auto-save to the config file and restore on next load.")
  local acc = tab:AddAccordion({ Title = "Inside an accordion", Icon = "rows-3", Expanded = false })
  acc:AddTextBox({ Text = "Nested", Placeholder = "…" })
  local acc2 = tab:AddAccordion({ Title = "Expanded by default", Icon = "rows-3", Expanded = true })
  acc2:AddTextBox({ Text = "Nested", Placeholder = "…" })
end
