return function(window)
  local tab = window:AddTab({ Name = "Controls", Icon = "sliders-horizontal" })
  tab:AddSection("Inputs")
  tab:AddToggle({ Text = "Toggle", Default = true })
  tab:AddSlider({ Text = "Slider", Min = 0, Max = 100, Default = 50 })
  tab:AddNumberBox({ Text = "Number", Default = 10, Min = 0, Max = 100 })
  tab:AddSelectBox({ Text = "Select", Options = { "Alpha", "Beta", "Gamma" }, Default = "Alpha" })
  tab:AddSelectBox({ Text = "Multi-select", Options = { "X", "Y", "Z" }, Multi = true, Default = { "X" } })
  tab:AddKeybind({ Text = "Keybind", Default = Enum.KeyCode.E })
  tab:AddColorPicker({ Text = "Color", Default = Color3.fromRGB(120, 160, 255) })
  tab:AddTextBox({ Text = "Text", Placeholder = "Type something…" })
  tab:AddProgressBar({ Default = 0.6 })
end
