// Generates core/icons.lua DATA from latte-soft/lucide-roblox 48px table.
// Usage: node scripts/build-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";

const UPSTREAM = "https://raw.githubusercontent.com/latte-soft/lucide-roblox/master/lib/Icons.luau";
const manifest = readFileSync("scripts/icons.manifest.txt", "utf8")
  .split("\n").map(s => s.trim()).filter(Boolean);

const src = await fetch(UPSTREAM).then(r => {
  if (!r.ok) throw new Error("fetch upstream failed: " + r.status);
  return r.text();
});

// Isolate ONLY the 48px block (between ["48px"] and ["256px"]); otherwise 256px
// entries with the same names overwrite (last-wins) and we'd ship w=256 coords.
const startIdx = src.indexOf('["48px"]');
const endIdx = src.indexOf('["256px"]');
if (startIdx === -1) throw new Error('could not find ["48px"] table in upstream');
const block = src.slice(startIdx, endIdx === -1 ? undefined : endIdx);

// Keys come in two forms: bracketed for hyphenated names (["chevron-right"] = ...)
// and bare identifiers for valid names (house = ...). Match both.
// Value shape: {id, {w, h}, {x, y}}
const re = /(?:\["([^"]+)"\]|([A-Za-z_][A-Za-z0-9_]*))\s*=\s*\{\s*(\d+)\s*,\s*\{\s*(\d+)\s*,\s*(\d+)\s*\}\s*,\s*\{\s*(\d+)\s*,\s*(\d+)\s*\}/g;
const all = new Map();
let m;
while ((m = re.exec(block))) {
  const name = m[1] || m[2];
  all.set(name, { id: +m[3], w: +m[4], h: +m[5], x: +m[6], y: +m[7] });
}

const lines = [];
const missing = [];
for (const name of manifest) {
  const e = all.get(name);
  if (!e) { missing.push(name); continue; }
  lines.push(`  ["${name}"] = { id = ${e.id}, w = ${e.w}, h = ${e.h}, x = ${e.x}, y = ${e.y} },`);
}
if (missing.length) console.warn("WARNING: not in upstream:", missing.join(", "));

const header = `-- AUTO-GENERATED by scripts/build-icons.mjs from latte-soft/lucide-roblox (ISC/MIT).
-- Curated subset; edit scripts/icons.manifest.txt then run \`make icons\`.
local DATA = {
${lines.join("\n")}
}
`;
const tail = readFileSync("core/icons.lua", "utf8").split("local Icons = { data = DATA }")[1];
writeFileSync("core/icons.lua", header + "\nlocal Icons = { data = DATA }" + tail);
console.log(`Wrote ${lines.length} icons to core/icons.lua (${missing.length} missing).`);
